// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace schedule
{
    public partial class ProgramTest
    {
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
public void new_list936()
{
    LinkedList<Ele> linkedList;
    linkedList = this.new_list();
    Assert.IsNotNull((object)linkedList);
    Assert.AreEqual<int>(0, linkedList.Count);
    Assert.IsNull(linkedList.First);
    Assert.IsNull(linkedList.Last);
}
    }
}
