// <copyright file="StringExtensionsTest.Capitalize.g.cs" company="MSIT">Copyright © MSIT 2008</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Framework.Exceptions;

namespace Strings
{
	public partial class StringExtensionsTest
	{
[TestMethod]
[PexGeneratedBy(typeof(StringExtensionsTest))]
public void Capitalize983()
{
    string s;
    s = this.Capitalize("");
    Assert.AreEqual<string>("", s);
}
[TestMethod]
[PexGeneratedBy(typeof(StringExtensionsTest))]
[PexRaisedException(typeof(FormatException))]
public void CapitalizeThrowsFormatException988()
{
    string s;
    s = this.Capitalize("jksdfhlasfhlskjfhsaljf");
}
[TestMethod]
[PexGeneratedBy(typeof(StringExtensionsTest))]
public void Capitalize870()
{
    string s;
    s = this.Capitalize("\0");
    Assert.AreEqual<string>("", s);
}
[TestMethod]
[PexGeneratedBy(typeof(StringExtensionsTest))]
public void Capitalize704()
{
    string s;
    s = this.Capitalize(".");
    Assert.AreEqual<string>("_", s);
}
[TestMethod]
[PexGeneratedBy(typeof(StringExtensionsTest))]
public void Capitalize439()
{
    string s;
    s = this.Capitalize("a");
    Assert.AreEqual<string>("A", s);
}
[TestMethod]
[PexGeneratedBy(typeof(StringExtensionsTest))]
public void Capitalize351()
{
    string s;
    s = this.Capitalize("h\0");
    Assert.AreEqual<string>("H", s);
}
[TestMethod]
[PexGeneratedBy(typeof(StringExtensionsTest))]
public void Capitalize255()
{
    string s;
    s = this.Capitalize("h\u8061\0");
    Assert.AreEqual<string>("H\u8061", s);
}
[TestMethod]
[PexGeneratedBy(typeof(StringExtensionsTest))]
public void Capitalize233()
{
    string s;
    s = this.Capitalize("haa");
    Assert.AreEqual<string>("Haa", s);
}
[TestMethod]
[PexGeneratedBy(typeof(StringExtensionsTest))]
public void Capitalize928()
{
    string s;
    s = this.Capitalize("h.\0");
    Assert.AreEqual<string>("H_", s);
}
[TestMethod]
[PexGeneratedBy(typeof(StringExtensionsTest))]
public void Capitalize140()
{
    string s;
    s = this.Capitalize("h..");
    Assert.AreEqual<string>("H__", s);
}
[TestMethod]
[PexGeneratedBy(typeof(StringExtensionsTest))]
public void Capitalize393()
{
    string s;
    s = this.Capitalize("haaaAaa\u8061\0\0");
    Assert.AreEqual<string>("HaaaAaa\u8061", s);
}
	}
}
