// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Framework.Exceptions;

namespace Strings
{
	public partial class TestObjectTest
	{
[TestMethod]
[PexGeneratedBy(typeof(TestObjectTest))]
public void Do522()
{
    string s;
    s = this.Do(0, (string)null);
    Assert.AreEqual<string>("null0", s);
}
[TestMethod]
[PexGeneratedBy(typeof(TestObjectTest))]
public void Do245()
{
    string s;
    s = this.Do(1, (string)null);
    Assert.AreEqual<string>("null1", s);
}
[TestMethod]
[PexGeneratedBy(typeof(TestObjectTest))]
[PexRaisedException(typeof(PexAssertFailedException))]
public void DoThrowsPexAssertFailedException857()
{
    string s;
    s = this.Do(int.MinValue, (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(TestObjectTest))]
public void Do809()
{
    string s;
    s = this.Do(0, "\0");
    Assert.AreEqual<string>("\00", s);
}
	}
}
