// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Edu.Nlu.Sir.Siemens.Replace
{
    public partial class BaseVersionTest
    {
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void omatchThrowsNullReferenceException448()
{
    bool b;
    int i = 0;
    b = this.omatch((string)null, ref i, (string)null, 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void omatch142()
{
    bool b;
    int i = 0;
    b = this.omatch("\0", ref i, "\0", 0);
    Assert.AreEqual<bool>(false, b);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void omatchThrowsIndexOutOfRangeException862()
{
    bool b;
    int i = 128;
    b = this.omatch("", ref i, "\0", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void omatch822()
{
    bool b;
    int i = 0;
    b = this.omatch("\u0001", ref i, "?", 0);
    Assert.AreEqual<bool>(true, b);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void omatch367()
{
    bool b;
    int i = 0;
    b = this.omatch("\n", ref i, "?", 0);
    Assert.AreEqual<bool>(false, b);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void omatchThrowsIndexOutOfRangeException327()
{
    bool b;
    int i = 0;
    b = this.omatch("\u0001", ref i, "c", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void omatch743()
{
    bool b;
    int i = 0;
    b = this.omatch("\u0001", ref i, "%", 0);
    Assert.AreEqual<bool>(true, b);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void omatch845()
{
    bool b;
    int i = 0;
    b = this.omatch("\u0001", ref i, "[\0", 0);
    Assert.AreEqual<bool>(false, b);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void omatch879()
{
    bool b;
    int i = 2;
    b = this.omatch("\0\0\u0001", ref i, "%", 0);
    Assert.AreEqual<bool>(false, b);
    Assert.AreEqual<int>(2, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void omatch515()
{
    bool b;
    int i = 0;
    b = this.omatch("\u0001", ref i, "[\u0001\0", 0);
    Assert.AreEqual<bool>(false, b);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void omatch847()
{
    bool b;
    int i = 0;
    b = this.omatch("\u0001", ref i, "$", 0);
    Assert.AreEqual<bool>(false, b);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void omatch772()
{
    bool b;
    int i = 0;
    b = this.omatch("\u0001", ref i, "[\u0001\u0001", 0);
    Assert.AreEqual<bool>(true, b);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void omatch973()
{
    bool b;
    int i = 0;
    b = this.omatch("\n", ref i, "$", 0);
    Assert.AreEqual<bool>(true, b);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void omatch88()
{
    bool b;
    int i = 0;
    b = this.omatch("\n", ref i, "!", 0);
    Assert.AreEqual<bool>(false, b);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void omatch714()
{
    bool b;
    int i = 0;
    b = this.omatch("\u0001", ref i, "[\u0005\0\0\0\0\0", 0);
    Assert.AreEqual<bool>(false, b);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void omatch356()
{
    bool b;
    int i = 0;
    b = this.omatch("\u0001", ref i, "!\0", 0);
    Assert.AreEqual<bool>(true, b);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void omatch499()
{
    bool b;
    int i = 0;
    b = this.omatch("\u0001", ref i, "c\0", 0);
    Assert.AreEqual<bool>(false, b);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void omatch130()
{
    bool b;
    int i = 0;
    b = this.omatch("\u0001", ref i, "c\u0001", 0);
    Assert.AreEqual<bool>(true, b);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void omatchThrowsIndexOutOfRangeException667()
{
    bool b;
    int i = 0;
    b = this.omatch("\u0001", ref i, "!", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void omatchThrowsExitException784()
{
    bool b;
    int i = 0;
    b = this.omatch("\u0001", ref i, "\u0001", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void omatchThrowsIndexOutOfRangeException255()
{
    bool b;
    int i = 0;
    b = this.omatch("\u0001", ref i, "[\u8000", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void omatch651()
{
    bool b;
    int i = 0;
    b = this.omatch("\n", ref i, "!\0", 0);
    Assert.AreEqual<bool>(false, b);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void omatch237()
{
    bool b;
    int i = 0;
    b = this.omatch("\u0001", ref i, "$\0", 0);
    Assert.AreEqual<bool>(false, b);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void omatch128()
{
    bool b;
    int i = 0;
    b = this.omatch("\n", ref i, "$\0", 0);
    Assert.AreEqual<bool>(true, b);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void omatch955()
{
    bool b;
    int i = 0;
    b = this.omatch("\u0001", ref i, "%\0", 0);
    Assert.AreEqual<bool>(true, b);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void omatch369()
{
    bool b;
    int i = 0;
    b = this.omatch("\0", ref i, "c\u0001", 0);
    Assert.AreEqual<bool>(false, b);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void omatch611()
{
    bool b;
    int i = 0;
    b = this.omatch("\u0001", ref i, "?\0", 0);
    Assert.AreEqual<bool>(true, b);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void omatch621()
{
    bool b;
    int i = 0;
    b = this.omatch("\n", ref i, "?\0", 0);
    Assert.AreEqual<bool>(false, b);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void omatchThrowsIndexOutOfRangeException275()
{
    bool b;
    int i = 0;
    b = this.omatch("\u0001", ref i, "[", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void omatchThrowsExitException475()
{
    bool b;
    int i = 0;
    b = this.omatch("\u0001", ref i, "*", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void omatch422()
{
    bool b;
    int i = 2;
    b = this.omatch("\u0001\u0001\u0001", ref i, "%", 0);
    Assert.AreEqual<bool>(false, b);
    Assert.AreEqual<int>(2, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void omatchThrowsIndexOutOfRangeException991()
{
    bool b;
    int i = 0;
    b = this.omatch("\u0001\u0001\u0001", ref i, "%", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void omatch862()
{
    bool b;
    int i = 0;
    b = this.omatch("\u0001\u0001\u0001", ref i, "%\0", 0);
    Assert.AreEqual<bool>(true, b);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void omatch865()
{
    bool b;
    int i = 0;
    b = this.omatch("\u0001\u0001", ref i, "c\u0001\0", 0);
    Assert.AreEqual<bool>(true, b);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void omatch555()
{
    bool b;
    int i = 0;
    b = this.omatch("\0", ref i, "$\0", 0);
    Assert.AreEqual<bool>(false, b);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void omatchThrowsIndexOutOfRangeException394()
{
    bool b;
    int i = 0;
    b = this.omatch("", ref i, "$\0", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void omatch575()
{
    bool b;
    int i = 2;
    b = this.omatch("\u0001\u0001\u0001", ref i, "%\0", 0);
    Assert.AreEqual<bool>(false, b);
    Assert.AreEqual<int>(2, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void omatchThrowsExitException407()
{
    bool b;
    int i = 0;
    b = this.omatch("\u0001", ref i, "\0\0", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void omatchThrowsExitException196()
{
    bool b;
    int i = 0;
    b = this.omatch("\u0001", ref i, "*\0", 0);
}
    }
}
