// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Edu.Nlu.Sir.Siemens.Replace
{
    public partial class BaseVersionTest
    {
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[ExpectedException(typeof(ArgumentException))]
public void sublineThrowsArgumentException753()
{
    this.subline("\0", "\0", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void sublineThrowsExitException832()
{
    this.subline("\u0001\0\0", "\u0001", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException553()
{
    this.subline("\u0001\0\0", "c", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException158()
{
    this.subline("\u0001\0\0", "!\0", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[ExpectedException(typeof(ArgumentException))]
public void sublineThrowsArgumentException829()
{
    this.subline("*\0\0", "*", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException226()
{
    this.subline("\u0001\0\0", "c\u0001", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException504()
{
    this.subline("\u0001!!", "!\u0001\0", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void sublineThrowsExitException713()
{
    this.subline("*\0\0", "*\0", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException629()
{
    this.subline("\u0001\0\0", "[\u0001\u0001", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException417()
{
    this.subline("\u0001\0\0\0\0\0\0\0\0", "\0", "\u0001\u0001");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void sublineThrowsExitException762()
{
    this.subline("\u0001\0\0", "%\u0001", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void sublineThrowsExitException492()
{
    this.subline("\0\0\0", "*\0\0", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException174()
{
    this.subline("\u0001\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "\0", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void sublineThrowsNullReferenceException155()
{
    this.subline("\u0001[[[[[[[[[", "[\u0001\u0001\0\0\0\0", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException651()
{
    this.subline("\u0001!!", "!\u0002\0\0", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[ExpectedException(typeof(ArgumentException))]
public void sublineThrowsArgumentException931()
{
    this.subline("\u0001**", "*c\0", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void sublineThrowsNullReferenceException233()
{
    this.subline("\u0001\0\0\0\0\0\0\0\0", "%\0", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void sublineThrowsNullReferenceException170()
{
    this.subline("\u0001********", "*c\0\0", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException433()
{
    this.subline("\u0001**", "*?", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException595()
{
    this.subline("\u0001\0\0", "!", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException192()
{
    this.subline("\n$$", "$", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException567()
{
    this.subline("\u0001**", "*c\u0001", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException608()
{
    this.subline("\u0001%%", "%", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException199()
{
    this.subline("\u0001[[", "[", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException242()
{
    this.subline("\u0001??", "?", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException61()
{
    this.subline("\n**", "*?", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException907()
{
    this.subline("\u0001\0\0", "!\uffff", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException488()
{
    this.subline("\u0001\u0001\0", "*c\u0001", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void subline815()
{
    this.subline("\0\0\0", "*\0", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException920()
{
    this.subline("\u0001\0\0\0\0\0\0\0\0", "\0", "");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException917()
{
    this.subline("\n**", "*!", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException555()
{
    this.subline("\u0001\u0001!!", "!\u0002\0\0!", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void sublineThrowsNullReferenceException792()
{
    this.subline((string)null, "", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException737()
{
    this.subline("\u0001\u0001*", "!\u0001\0*%", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException563()
{
    this.subline("\u0001**", "*$", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void sublineThrowsExitException519()
{
    this.subline("\u0001\u0001\0", "?\u0001", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void sublineThrowsExitException627()
{
    this.subline("\u0001\0\0", "**", (string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException257()
{
    this.subline("\u0001\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "\0", "\0\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void sublineThrowsExitException169()
{
    this.subline("\u0001\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "\u0001", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException76()
{
    this.subline("\u0001\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "$", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException954()
{
    this.subline("\u0001\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "[", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException152()
{
    this.subline("\u0001\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "*", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException935()
{
    this.subline("\u0001\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "!", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void subline246()
{
    this.subline("\0\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "\0", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void sublineThrowsExitException259()
{
    this.subline("\u0001\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "**", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException531()
{
    this.subline("\u0001\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "%", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException59501()
{
    this.subline("\n\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "!", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException231()
{
    this.subline("\u0001\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "[[", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException64()
{
    this.subline
        ("\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001", "[\0", "\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException796()
{
    this.subline("\n\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "$", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException516()
{
    this.subline("\u0001\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "?", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException643()
{
    this.subline("\n\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "?", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException187()
{
    this.subline("\u0001\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "c", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException248()
{
    this.subline("\u0001\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "[\u0001\u0001", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException291()
{
    this.subline("\u0001\u0001\u0001\u0001", "[\u0001\0", "\u0001\u0001\u0001\u0001");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException234()
{
    this.subline("\u0001\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "cc", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException868()
{
    this.subline("\u0001\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "c\u0001", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException240()
{
    this.subline("\u0001\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "%%", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException607()
{
    this.subline("\u0001\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "c\u0001\0", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException72()
{
    this.subline("\u0001\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "!\u0001\0", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException224()
{
    this.subline("\n\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "$$", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException327()
{
    this.subline("\u0001\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "*?", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException975()
{
    this.subline("\u0001\0\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "*?", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException883()
{
    this.subline("\u0001\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "*$", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException817()
{
    this.subline("\u0001\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "*c\0\0", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException941()
{
    this.subline("\u0001\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "*c\0$", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException385()
{
    this.subline("\u0001\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "??", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException969()
{
    this.subline("\u0001\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "*c\0\0", "\0\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException700()
{
    this.subline("\n\n\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "!", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException767()
{
    this.subline("\u0001\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "!\u0001\u0001", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException48()
{
    this.subline("\n\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "*!", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException116()
{
    this.subline
        ("\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001", "*!\0", "\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException669()
{
    this.subline("\n\uffff\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "?%", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException800()
{
    this.subline("\n\n\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "?", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException206()
{
    this.subline("\u0001\u0001\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "*[\u0001\u0001\0\0\0", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException78()
{
    this.subline("\u0001\u0001\uffff\uffff\uffff\uffff\uffff\uffff\uffff", "*c\0*c\u0001", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException400()
{
    this.subline("\u0001", "[\u0001\u0001\0\0\0\0", "\0");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException641()
{
    this.subline("\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001", 
                 "*c\0*$*[\0*$$\0", "\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException869()
{
    this.subline("\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001", "*c\0*$*[\0!\0\0\0", "\uffff\u0001\0**");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void sublineThrowsExitException518()
{
    this.subline("\n\uffff\0\uffff\uffff\uffff\uffff\uffff\uffff", "?*\0", "\uffff\u0001\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException306()
{
    this.subline("\n\u0001\0", "?*", "\0\0");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException966()
{
    this.subline("\n\u0001\0", "?*!", "\0\0\0");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException20601()
{
    this.subline("\n\u0001\0", "?*[", "\0\0\0");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void subline252()
{
    this.subline("\u0001$\0", "$", "\u0001");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException30601()
{
    this.subline("\n\0\0", "$", "\0");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void sublineThrowsExitException203()
{
    this.subline("\u0001\u0001\0\0\0\0", "c\u0001\u0001", "\u0001\u0001\0");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException828()
{
    this.subline("\u0001\0\0", "\0", "\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException42()
{
    this.subline("\u0001\0\0", "%", "\u0001");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException371()
{
    this.subline("\n\u0001\0", "?**", "\0\0\0");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException732()
{
    this.subline("\u0001\u0001\0\0\0\0", "*?", "\u0001\u0001");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException964()
{
    this.subline("\u0001\0\0", "*", "\u0001");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException819()
{
    this.subline("\u0001\0\0", "[", "\u0001");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException214()
{
    this.subline("\u0001\0\0\0\0\0", "[\ubfff", "\u0001\0");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException143()
{
    this.subline("\u0001!\0", "!", "\u0001");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void subline474()
{
    this.subline("\n\0\0", "!", "\0");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException403()
{
    this.subline("\u0001[\0[[[", "[\u0001\u0001", "\u0001[\0");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void subline585()
{
    this.subline("\u0001\u0001\u0001\u0001\0\0\0\0\0\0\0\0\0\0", "[\u0001\0", "\u0001\u0001\u0001");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException734()
{
    this.subline("\u0001!!!!\0", "!\0", "\u0001!");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException147()
{
    this.subline("\n\0\0\0\0\0", "*?", "\0\0");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException831()
{
    this.subline("\u0001\0\0\0\0\0", "\0", "\uffff\uffff");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void sublineThrowsExitException350()
{
    this.subline("\u0001\u0001*********\0", "c\u0001**", "\u0001\u0001**");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException18()
{
    this.subline("\u0001\0", "c\u0001*c", "\0\0\0\0");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException175()
{
    this.subline("\u0001\u0001\0\0\0\0\0\0\0\0\0\0", "c\u0001!\0", "\u0001\u0001\0\0");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException976()
{
    this.subline("\u0001cccc\0", "*c\u0001", "\u0001cc");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void subline6()
{
    this.subline("\u0001****\0", "*%", "\u0001*");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException742()
{
    this.subline("\ncccccccccc\0", "*c\0!", "\0\0\0\0");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void subline173()
{
    this.subline("\u0001$$$$\0", "%$", "\u0001$");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void subline720()
{
    this.subline("\u0001$$$$$$$$$$\0", "*c\0$", "\u0001$$$");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException304()
{
    this.subline("\u0001\0\0\0\0\0", "%%", "\u0001\0");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void sublineThrowsExitException19()
{
    this.subline("\u0001\0\0", "\0", "\0");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void sublineThrowsIndexOutOfRangeException426()
{
    this.subline("\u0001\0\0\0\0\0", "c\0", "\u0001\0");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void sublineThrowsExitException634()
{
    this.subline("\u0001**********\0", "*c\0\0", "\0");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void subline27()
{
    this.subline("\u0001\u0001\0", "*?\0", "\0\0\0");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void subline193()
{
    this.subline("\u0001\0\0\0\0\0", "[\0", "\u0001\0");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void subline380()
{
    this.subline("\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\0\0", "*c\0*!\0c\0", "\0\0\0\0\0\0\0\0");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void subline840()
{
    this.subline("\n\u0001\u0001\n\0\0\0\0\0\0\0\0\0\0", "$\0", "\0");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[ExpectedException(typeof(ArgumentException))]
public void sublineThrowsArgumentException720()
{
    this.subline("\u0001\u0001\u0001\0\0\0\0\0\0\0\0\0", "c\u0001*!\0", "\u0001\u0001\u0001\0\0");
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void sublineThrowsExitException965()
{
    this.subline("\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\0", "*c\0*!\0\u0001", "\0\0\0\0\0\0\0");
}
    }
}
