// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Edu.Nlu.Sir.Siemens.Replace
{
    public partial class BaseVersionTest
    {
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void amatchThrowsNullReferenceException206()
{
    int i;
    i = this.amatch((string)null, 0, (string)null, 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void amatchThrowsNullReferenceException389()
{
    int i;
    i = this.amatch((string)null, 0, "\0", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch6()
{
    int i;
    i = this.amatch("\0", -2, "\0", 0);
    Assert.AreEqual<int>(-2, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void amatchThrowsIndexOutOfRangeException11()
{
    int i;
    i = this.amatch("\u0001", -2, "\u0001", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void amatchThrowsIndexOutOfRangeException909()
{
    int i;
    i = this.amatch("\u0001cc", 0, "c", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[ExpectedException(typeof(ArgumentException))]
public void amatchThrowsArgumentException929()
{
    int i;
    i = this.amatch("\u0001%%", 0, "%", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch937()
{
    int i;
    i = this.amatch("%%%%\u0001%%", 4, "%", 0);
    Assert.AreEqual<int>(-1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[ExpectedException(typeof(ArgumentException))]
public void amatchThrowsArgumentException673()
{
    int i;
    i = this.amatch("\u0001??", 0, "?", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch886()
{
    int i;
    i = this.amatch("\u0001\0\0", 0, "$", 0);
    Assert.AreEqual<int>(-1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[ExpectedException(typeof(ArgumentException))]
public void amatchThrowsArgumentException640()
{
    int i;
    i = this.amatch("\u0001!!", 0, "!", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[ExpectedException(typeof(ArgumentException))]
public void amatchThrowsArgumentException65()
{
    int i;
    i = this.amatch("*", -2, "*", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[ExpectedException(typeof(ArgumentException))]
public void amatchThrowsArgumentException787()
{
    int i;
    i = this.amatch("\u0001[[", 0, "[", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch783()
{
    int i;
    i = this.amatch("\n!!", 0, "!", 0);
    Assert.AreEqual<int>(-1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch181()
{
    int i;
    i = this.amatch("\n??", 0, "?", 0);
    Assert.AreEqual<int>(-1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch945()
{
    int i;
    i = this.amatch("\0\0\0", 0, "\u0001", 0);
    Assert.AreEqual<int>(-1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch742()
{
    int i;
    i = this.amatch("\u0001[[", 0, "[\0\0", 0);
    Assert.AreEqual<int>(-1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch923()
{
    int i;
    i = this.amatch("\0\0\0", 0, "**\0", 0);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch869()
{
    int i;
    i = this.amatch("\u0001[[", 0, "[\u0001\0", 0);
    Assert.AreEqual<int>(-1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void amatchThrowsIndexOutOfRangeException547()
{
    int i;
    i = this.amatch("\u0001[[", 0, "[\u0001\u0001", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[ExpectedException(typeof(ArgumentException))]
public void amatchThrowsArgumentException600()
{
    int i;
    i = this.amatch("\u0001[[", 0, "\0[\u8041", 1);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[ExpectedException(typeof(ArgumentException))]
public void amatchThrowsArgumentException958()
{
    int i;
    i = this.amatch("\n$$", 0, "$", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void amatchThrowsIndexOutOfRangeException380()
{
    int i;
    i = this.amatch("\u0001\u0001!", 0, "*!\0", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch909()
{
    int i;
    i = this.amatch("\u0001cc", 0, "c\0\0", 0);
    Assert.AreEqual<int>(-1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch689()
{
    int i;
    i = this.amatch("\u0001cc", 0, "c\u0001\0", 0);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch75()
{
    int i;
    i = this.amatch("\n\0\0", 0, "$\0\0", 0);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch244()
{
    int i;
    i = this.amatch("\0\0\0", 0, "*?\0", 0);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void amatchThrowsIndexOutOfRangeException730()
{
    int i;
    i = this.amatch("\u0001**", 0, "*?\0", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[ExpectedException(typeof(ArgumentException))]
public void amatchThrowsArgumentException735()
{
    int i;
    i = this.amatch("\u0002\u0003*", 0, "*c\u0002", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void amatchThrowsExitException819()
{
    int i;
    i = this.amatch("\u0001cc", 0, "c\u0001\u0001", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch700()
{
    int i;
    i = this.amatch("\0\0\0", 0, "*c\0\u0001\0\0\0", 0);
    Assert.AreEqual<int>(-1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void amatch505()
{
    int i;
    i = this.amatch("\u0001\0\0", 0, "*%", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch88()
{
    int i;
    i = this.amatch("\u0001\u0001%", 0, "c\u0001%", 0);
    Assert.AreEqual<int>(-1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch295()
{
    int i;
    i = this.amatch("\u0001%%", 0, "%\0", 0);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void amatch186()
{
    int i;
    i = this.amatch("\n**", 0, "*$", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch953()
{
    int i;
    i = this.amatch("\u0001$$", 0, "*$$", 0);
    Assert.AreEqual<int>(-1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch902()
{
    int i;
    i = this.amatch("****\u0001**", 4, "*%%", 0);
    Assert.AreEqual<int>(-1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch50501()
{
    int i;
    i = this.amatch("\n\0\0", 0, "%$\0", 0);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[ExpectedException(typeof(ArgumentException))]
public void amatchThrowsArgumentException212()
{
    int i;
    i = this.amatch("\n\0\0", 0, "*?*", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch754()
{
    int i;
    i = this.amatch("****\n**", 4, "*?*%\0", 0);
    Assert.AreEqual<int>(4, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch992()
{
    int i;
    i = this.amatch("\u0001%%", 0, "%%\0", 0);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch624()
{
    int i;
    i = this.amatch("****\n**", 4, "*?*%%", 0);
    Assert.AreEqual<int>(-1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[ExpectedException(typeof(ArgumentException))]
public void amatchThrowsArgumentException57()
{
    int i;
    i = this.amatch("\n**", 0, "\0*?*?", 1);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch69()
{
    int i;
    i = this.amatch("\0\n\0\0\0\0\0\0\0\0", 1, "*?*%*[\0$*[\0\0", 0);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch408()
{
    int i;
    i = this.amatch("*\n*****", 1, "*?*%*?\0", 0);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void amatchThrowsExitException80301()
{
    int i;
    i = this.amatch("\n\0\0", 0, "*?*\0\0\0\0", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch870()
{
    int i;
    i = this.amatch("\u0200\u0001\0", 0, "\0\0*!\u0001\0\0", 2);
    Assert.AreEqual<int>(2, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void amatchThrowsIndexOutOfRangeException796()
{
    int i;
    i = this.amatch("\u0002\u0002\u0003", 0, "*c\u0002", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void amatchThrowsIndexOutOfRangeException929()
{
    int i;
    i = this.amatch("\0\0\0\0", 0, "*c\0*c\0", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void amatchThrowsIndexOutOfRangeException409()
{
    int i;
    i = this.amatch("\u0001\0\0", 0, "\0*!\u0003\0\0\u0001", 1);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void amatchThrowsIndexOutOfRangeException449()
{
    int i;
    i = this.amatch("\u0001\u0001[", 0, "\0\0\0*[\u0001\u0001", 3);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void amatchThrowsExitException810()
{
    int i;
    i = this.amatch("\u0001\0\0", 0, "\u0001", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void amatchThrowsExitException356()
{
    int i;
    i = this.amatch("*\n****", 1, "*?*%*[\0$$******", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void amatchThrowsIndexOutOfRangeException744()
{
    int i;
    i = this.amatch("\0**", 0, "*[\0", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch258()
{
    int i;
    i = this.amatch("\u0004$$$$\0$", 0, "\0$\0\0", 1);
    Assert.AreEqual<int>(-1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch300()
{
    int i;
    i = this.amatch("\u0004\0\0\0\0\0\0", 0, "\0?\0\0", 1);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void amatchThrowsIndexOutOfRangeException94()
{
    int i;
    i = this.amatch("\n\0*", 0, "*!\0", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch417()
{
    int i;
    i = this.amatch("\u0004cccc\0c", 0, "\0c\0\0", 1);
    Assert.AreEqual<int>(-1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch61()
{
    int i;
    i = this.amatch("cc\u0100\0c", 2, "c\u0100\0\0", 0);
    Assert.AreEqual<int>(3, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void amatchThrowsIndexOutOfRangeException971()
{
    int i;
    i = this.amatch("\u4000\u0010\0", 0, "*[\u0004\0\0\0\u4000", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void amatch373()
{
    int i;
    i = this.amatch("\n*\0", 0, "\0*?*%", 1);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void amatchThrowsIndexOutOfRangeException999()
{
    int i;
    i = this.amatch("\u0004\u0004\0", 0, "*[\u0004\0\0\0\u0004", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch962()
{
    int i;
    i = this.amatch("????\n????????\0?", 4, "*?*%*?\0\0\0\0\0\0\0\0\0", 0);
    Assert.AreEqual<int>(4, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void amatch790()
{
    int i;
    i = this.amatch("\n\0*", 0, "*$\0", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch230()
{
    int i;
    i = this.amatch("\u0001\0%", 0, "%%\0", 0);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch963()
{
    int i;
    i = this.amatch("\n\u0001??\0?????????", 0, "*?*c\n\0", 0);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch410()
{
    int i;
    i = this.amatch("*\n*\0****", 1, "*?*%*[\0$*%\0\0\0\0\0", 0);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch123()
{
    int i;
    i = this.amatch("\n\n ??\0?", 0, "\0\0\0\0*?*c\n\0", 4);
    Assert.AreEqual<int>(2, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch299()
{
    int i;
    i = this.amatch("*\0**\n**", 4, "*?*%*[\0%***", 0);
    Assert.AreEqual<int>(-1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch29901()
{
    int i;
    i = this.amatch("\u0001\u0001\0", 0, "*?\0", 0);
    Assert.AreEqual<int>(2, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch517()
{
    int i;
    i = this.amatch("???\0\n?????", 4, "**?*%*[\0*!\u0002**!", 1);
    Assert.AreEqual<int>(-1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void amatchThrowsIndexOutOfRangeException511()
{
    int i;
    i = this.amatch("?\n?\0", 1, "*?*%*[\0*!\u0002\0\0*!\0", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void amatch268()
{
    int i;
    i = this.amatch("????\n\0?", 4, "\0*?*%*c\u0001c******", 1);
    Assert.AreEqual<int>(-1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void amatchThrowsIndexOutOfRangeException173()
{
    int i;
    i = this.amatch("\n\0\0", 0, "*?*[\0", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void amatchThrowsIndexOutOfRangeException326()
{
    int i;
    i = this.amatch("\u4000\0**", 0, "\0\0*[\ud7f8", 2);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void amatchThrowsIndexOutOfRangeException515()
{
    int i;
    i = this.amatch("\n?\0", 0, "\0*?*?", 1);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void amatchThrowsIndexOutOfRangeException603()
{
    int i;
    i = this.amatch("*\0******", 1, "\0\0\0\0\0\0\0\0*", 8);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void amatchThrowsIndexOutOfRangeException340()
{
    int i;
    i = this.amatch("\u0001*\0**", 0, "\0*[", 1);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void amatchThrowsIndexOutOfRangeException166()
{
    int i;
    i = this.amatch("\0***", 0, "*c\0*[\0", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void amatchThrowsExitException815()
{
    int i;
    i = this.amatch("\n?\0", 0, "\0*?**", 1);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void amatchThrowsIndexOutOfRangeException195()
{
    int i;
    i = this.amatch("\0\0\0\0\n\0\0", 4, "\0*?*%", 1);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void amatchThrowsExitException49()
{
    int i;
    i = this.amatch("\u0001\0\0", 0, "**\0", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void amatchThrowsExitException985()
{
    int i;
    i = this.amatch("\0**", 0, "*\0\0", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void amatchThrowsExitException478()
{
    int i;
    i = this.amatch("*\0\0", 0, "*\0", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void amatchThrowsExitException408()
{
    int i;
    i = this.amatch("***\0****\n**", 8, "*?*%*[\0$*[\0$**", 0);
}
    }
}
