// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Edu.Nlu.Sir.Siemens.Replace
{
    public partial class BaseVersionTest
    {
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void patsizeThrowsNullReferenceException905()
{
    int i;
    i = this.patsize((string)null, 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void patsize716()
{
    int i;
    i = this.patsize("%\0", 0);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void patsize174()
{
    int i;
    i = this.patsize("?\0", 0);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void patsize708()
{
    int i;
    i = this.patsize("*\0", 0);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void patsize328()
{
    int i;
    i = this.patsize("[\0", 0);
    Assert.AreEqual<int>(2, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void patsize56()
{
    int i;
    i = this.patsize("!\0", 0);
    Assert.AreEqual<int>(2, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void patsize366()
{
    int i;
    i = this.patsize("c\0", 0);
    Assert.AreEqual<int>(2, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void patsize547()
{
    int i;
    i = this.patsize("$\0", 0);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void patsizeThrowsIndexOutOfRangeException656()
{
    int i;
    i = this.patsize("", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void patsizeThrowsIndexOutOfRangeException46()
{
    int i;
    i = this.patsize("", int.MinValue);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void patsizeThrowsIndexOutOfRangeException209()
{
    int i;
    i = this.patsize("[", 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void patsizeThrowsIndexOutOfRangeException967()
{
    int i;
    i = this.patsize("", int.MaxValue);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void patsizeThrowsExitException752()
{
    int i;
    i = this.patsize("\0\0", 0);
}
    }
}
