// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Framework;
using System.IO;
using System.IO.Moles;

namespace Edu.Nlu.Sir.Siemens.Replace
{
    public partial class BaseVersionTest
    {
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void MainThrowsNullReferenceException895()
{
    string[] ss = new string[2];
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException302()
{
    string[] ss = new string[2];
    ss[0] = "\0";
    ss[1] = "\0";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException148()
{
    string[] ss = new string[2];
    ss[0] = "";
    ss[1] = "";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException773()
{
    string[] ss = new string[2];
    ss[0] = "[\u0001";
    ss[1] = "[\u0001";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException222()
{
    string[] ss = new string[2];
    ss[0] = "%\u0001";
    ss[1] = "%\u0001";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException714()
{
    string[] ss = new string[2];
    ss[0] = "?\u0001";
    ss[1] = "?\u0001";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void MainThrowsExitException139()
{
    string[] ss = new string[2];
    ss[0] = "\0\0";
    ss[1] = "\0\0";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException189()
{
    string[] ss = new string[2];
    ss[0] = "*\u0001";
    ss[1] = "*\u0001";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException893()
{
    string[] ss = new string[2];
    ss[0] = "$\u0001";
    ss[1] = "$\u0001";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void MainThrowsNullReferenceException812()
{
    this.Main((string[])null);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException66()
{
    string[] ss = new string[2];
    ss[0] = "[\u0001";
    ss[1] = "[-";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void MainThrowsArgumentOutOfRangeException354()
{
    string[] ss = new string[2];
    ss[0] = "[\u0001";
    ss[1] = "[\u0001\0";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException692()
{
    string[] ss = new string[2];
    ss[0] = "[\u0001";
    ss[1] = "[^";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException850()
{
    string[] ss = new string[2];
    ss[0] = "[\u0001";
    ss[1] = "[]";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException674()
{
    string[] ss = new string[2];
    ss[0] = "\u0001\u0001";
    ss[1] = "@\u0001";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void MainThrowsNullReferenceException700()
{
    string[] ss = new string[3];
    ss[0] = "$\u0001";
    ss[1] = "$\0";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException53()
{
    string[] ss = new string[3];
    ss[0] = "&";
    ss[1] = "$\0";
    ss[2] = "&";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException139()
{
    string[] ss = new string[2];
    ss[0] = "\u0001\u0001";
    ss[1] = "@t";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException10()
{
    string[] ss = new string[2];
    ss[0] = "\u0001\u0001";
    ss[1] = "@n";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IOException))]
public void MainThrowsIOException133()
{
    using (PexPConsoleInContext.Create())
    {
      IOException iOException;
      iOException = new IOException();
      IPexChoiceRecorder choices = PexChoose.Replay.Setup();
      choices.NextSegment(1).DefaultSession
          .At(1, "throw", (object)iOException);
      string[] ss = new string[2];
      ss[0] = "$\0";
      ss[1] = "$\0";
      this.Main(ss);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException655()
{
    string[] ss = new string[3];
    ss[0] = "@";
    ss[1] = "$\0";
    ss[2] = "@";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void MainThrowsArgumentOutOfRangeException909()
{
    string[] ss = new string[2];
    ss[0] = "[\u0001";
    ss[1] = "[-\0";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException511()
{
    string[] ss = new string[2];
    ss[0] = "[\u0001";
    ss[1] = "[-\u0001";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException393()
{
    string[] ss = new string[2];
    ss[0] = "[\u0001";
    ss[1] = "[--";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException956()
{
    string[] ss = new string[3];
    ss[0] = "\u0001\u0001";
    ss[1] = "$\0";
    ss[2] = "\u0001\u0001";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException442()
{
    string[] ss = new string[2];
    ss[0] = "[\u0001";
    ss[1] = "[-]*";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException538()
{
    string[] ss = new string[2];
    ss[0] = "[\u0001";
    ss[1] = "[-\u0001\u0001";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException9()
{
    string[] ss = new string[2];
    ss[0] = "[\u0001";
    ss[1] = "[-@\u0001";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException397()
{
    string[] ss = new string[2];
    ss[0] = "[\u0001";
    ss[1] = "[-][";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void MainThrowsArgumentOutOfRangeException311()
{
    string[] ss = new string[2];
    ss[0] = "[\u0001";
    ss[1] = "[-][\0";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException694()
{
    string[] ss = new string[2];
    ss[0] = "[\u0001";
    ss[1] = "[--\u0001";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException960()
{
    string[] ss = new string[2];
    ss[0] = "$\u0001";
    ss[1] = "$*";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException713()
{
    string[] ss = new string[2];
    ss[0] = "\u0001\u0001";
    ss[1] = "\u0001\u0001";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void MainThrowsExitException804()
{
    string[] ss = new string[2];
    ss[0] = "\0\u0001";
    ss[1] = "\0\u0001";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void MainThrowsExitException936()
{
    string[] ss = new string[3];
    ss[0] = "\0";
    ss[1] = "$\0";
    ss[2] = "\0";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void MainThrowsExitException844()
{
    string[] ss = new string[0];
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException853()
{
    using (PexPConsoleInContext.Create())
    {
      string[] ss = new string[2];
      ss[0] = "\u0001\u0001";
      ss[1] = "@\0";
      this.Main(ss);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException527()
{
    using (PexPConsoleInContext.Create())
    {
      string[] ss = new string[2];
      ss[0] = "\0";
      ss[1] = "$\0";
      this.Main(ss);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(SIOException))]
public void MainThrowsSIOException713()
{
    using (PexPConsoleInContext.Create())
    {
      SIOException sIOException;
      sIOException = new SIOException();
      IPexChoiceRecorder choices = PexChoose.Replay.Setup();
      choices.NextSegment(1).DefaultSession
          .At(1, "throw", (object)sIOException);
      string[] ss = new string[2];
      ss[0] = "@\0";
      ss[1] = "@\0";
      this.Main(ss);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException639()
{
    using (PexPConsoleInContext.Create())
    {
      IPexChoiceRecorder choices = PexChoose.Replay.Setup();
      choices.DefaultSession
          .At(0, "peeked", (object)true);
      string[] ss = new string[2];
      ss[0] = "\0";
      ss[1] = "$\0";
      this.Main(ss);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException837()
{
    using (PexPConsoleInContext.Create())
    {
      string[] ss = new string[3];
      ss[0] = "\u0001\u0001";
      ss[1] = "$\0";
      ss[2] = "\u0001\0";
      this.Main(ss);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(SIOException))]
public void MainThrowsSIOException625()
{
    using (PexPConsoleInContext.Create())
    {
      SIOException sIOException;
      sIOException = new SIOException();
      IPexChoiceRecorder choices = PexChoose.Replay.Setup();
      choices.NextSegment(1).DefaultSession
          .At(2, "lastPeek", (object)' ')
          .At(4, "throw", (object)sIOException);
      string[] ss = new string[2];
      ss[0] = "@\0";
      ss[1] = "@\0";
      this.Main(ss);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void MainThrowsArgumentOutOfRangeException70()
{
    string[] ss = new string[2];
    ss[0] = "$\u0001";
    ss[1] = "$[\0";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException34401()
{
    string[] ss = new string[2];
    ss[0] = "*\u0001";
    ss[1] = "**";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException620()
{
    string[] ss = new string[2];
    ss[0] = "$\u0001";
    ss[1] = "$$";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException901()
{
    string[] ss = new string[2];
    ss[0] = "*\u0001";
    ss[1] = "***";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException651()
{
    string[] ss = new string[3];
    ss[0] = "\u0001\u0001";
    ss[1] = "$\0";
    ss[2] = "\u0001&&";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException593()
{
    string[] ss = new string[2];
    ss[0] = "?\u0001";
    ss[1] = "?*";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException99()
{
    using (PexPConsoleInContext.Create())
    {
      string[] ss = new string[2];
      ss[0] = "?\u0001";
      ss[1] = "?\0";
      this.Main(ss);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException212()
{
    using (PexPConsoleInContext.Create())
    {
      string[] ss = new string[3];
      ss[0] = "?\0";
      ss[1] = "?\0";
      ss[2] = "?\0";
      this.Main(ss);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException5()
{
    using (PexPConsoleInContext.Create())
    {
      IPexChoiceRecorder choices = PexChoose.Replay.Setup();
      choices.DefaultSession
          .At(2, "lastPeek", (object)' ')
          .At(6, "lastPeek", (object)' ')
          .At(10, "lastPeek", (object)' ')
          .At(14, "lastPeek", (object)' ')
          .At(18, "lastPeek", (object)' ')
          .At(22, "lastPeek", (object)' ')
          .At(26, "lastPeek", (object)' ')
          .At(30, "lastPeek", (object)' ')
          .At(34, "lastPeek", (object)' ')
          .At(38, "lastPeek", (object)' ')
          .At(42, "lastPeek", (object)' ')
          .At(46, "lastPeek", (object)' ')
          .At(50, "lastPeek", (object)' ')
          .At(54, "lastPeek", (object)' ')
          .At(58, "lastPeek", (object)' ')
          .At(62, "lastPeek", (object)' ')
          .At(66, "lastPeek", (object)' ')
          .At(70, "lastPeek", (object)' ')
          .At(74, "lastPeek", (object)' ')
          .At(78, "lastPeek", (object)' ')
          .At(82, "lastPeek", (object)' ')
          .At(86, "lastPeek", (object)' ')
          .At(90, "lastPeek", (object)' ')
          .At(94, "lastPeek", (object)' ')
          .At(98, "lastPeek", (object)' ')
          .At(102, "lastPeek", (object)' ')
          .At(106, "lastPeek", (object)' ')
          .At(110, "lastPeek", (object)'@')
          .At(114, "lastPeek", (object)' ')
          .At(118, "lastPeek", (object)' ')
          .At(122, "lastPeek", (object)' ')
          .At(126, "lastPeek", (object)' ')
          .At(130, "lastPeek", (object)' ')
          .At(134, "lastPeek", (object)' ')
          .At(138, "lastPeek", (object)' ')
          .At(142, "lastPeek", (object)' ')
          .At(146, "lastPeek", (object)' ')
          .At(150, "lastPeek", (object)' ')
          .At(154, "lastPeek", (object)' ')
          .At(158, "lastPeek", (object)' ')
          .At(162, "lastPeek", (object)' ')
          .At(166, "lastPeek", (object)' ')
          .At(170, "lastPeek", (object)'@')
          .At(174, "lastPeek", (object)' ')
          .At(178, "lastPeek", (object)' ')
          .At(182, "lastPeek", (object)' ')
          .At(186, "lastPeek", (object)' ')
          .At(190, "lastPeek", (object)' ')
          .At(194, "lastPeek", (object)' ')
          .At(198, "lastPeek", (object)' ')
          .At(202, "lastPeek", (object)' ')
          .At(206, "lastPeek", (object)' ')
          .At(210, "lastPeek", (object)' ')
          .At(214, "lastPeek", (object)' ')
          .At(218, "lastPeek", (object)' ')
          .At(222, "lastPeek", (object)' ')
          .At(226, "lastPeek", (object)' ')
          .At(230, "lastPeek", (object)' ')
          .At(234, "lastPeek", (object)' ')
          .At(238, "lastPeek", (object)' ')
          .At(242, "lastPeek", (object)' ')
          .At(246, "lastPeek", (object)' ')
          .At(250, "lastPeek", (object)' ')
          .At(254, "lastPeek", (object)' ')
          .At(258, "lastPeek", (object)' ')
          .At(262, "lastPeek", (object)' ')
          .At(266, "lastPeek", (object)' ')
          .At(270, "lastPeek", (object)' ')
          .At(274, "lastPeek", (object)' ')
          .At(278, "lastPeek", (object)' ')
          .At(282, "lastPeek", (object)' ')
          .At(286, "lastPeek", (object)' ')
          .At(290, "lastPeek", (object)' ')
          .At(294, "lastPeek", (object)' ')
          .At(298, "lastPeek", (object)'@')
          .At(302, "lastPeek", (object)' ')
          .At(306, "lastPeek", (object)' ')
          .At(310, "lastPeek", (object)' ')
          .At(314, "lastPeek", (object)' ')
          .At(318, "lastPeek", (object)' ')
          .At(322, "lastPeek", (object)' ')
          .At(326, "lastPeek", (object)' ')
          .At(330, "lastPeek", (object)' ')
          .At(334, "lastPeek", (object)' ')
          .At(338, "lastPeek", (object)' ')
          .At(342, "lastPeek", (object)' ')
          .At(346, "lastPeek", (object)' ')
          .At(350, "lastPeek", (object)' ')
          .At(354, "lastPeek", (object)' ')
          .At(358, "lastPeek", (object)' ')
          .At(362, "lastPeek", (object)'@')
          .At(366, "lastPeek", (object)' ')
          .At(370, "lastPeek", (object)' ')
          .At(374, "lastPeek", (object)' ')
          .At(378, "lastPeek", (object)' ')
          .At(382, "lastPeek", (object)' ')
          .At(386, "lastPeek", (object)' ')
          .At(390, "lastPeek", (object)' ')
          .At(394, "lastPeek", (object)'@')
          .At(398, "lastPeek", (object)' ')
          .At(402, "lastPeek", (object)' ');
      string[] ss = new string[3];
      ss[0] = "\uffff\0";
      ss[1] = "?\0";
      ss[2] = "\uffff\0";
      this.Main(ss);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException244()
{
    string[] ss = new string[2];
    ss[0] = "?\u0001";
    ss[1] = "??";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException471()
{
    string[] ss = new string[2];
    ss[0] = "[\u0001";
    ss[1] = "[-@@@\u0001";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException601()
{
    string[] ss = new string[2];
    ss[0] = "[\u0001";
    ss[1] = "[-@@@@";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException936()
{
    string[] ss = new string[2];
    ss[0] = "%\u0001";
    ss[1] = "%%";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException136()
{
    using (PexPConsoleInContext.Create())
    {
      string[] ss = new string[3];
      ss[0] = "*\0";
      ss[1] = "*\0";
      ss[2] = "*\0";
      this.Main(ss);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException360()
{
    string[] ss = new string[2];
    ss[0] = "[\u0001";
    ss[1] = "[-@@@@\u0001";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void MainThrowsExitException961()
{
    string[] ss = new string[2];
    ss[0] = "%\u0001";
    ss[1] = "%*";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException52()
{
    using (PexPConsoleInContext.Create())
    {
      IPexChoiceRecorder choices = PexChoose.Replay.Setup();
      string[] ss = new string[2];
      ss[0] = "\u0001\u0001";
      ss[1] = "0\0";
      this.Main(ss);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException198()
{
    string[] ss = new string[2];
    ss[0] = "[\u0001";
    ss[1] = "[-@@@@t@@t";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException645()
{
    using (PexPConsoleInContext.Create())
    {
      string[] ss = new string[2];
      ss[0] = "%\u0001";
      ss[1] = "%\0";
      this.Main(ss);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException195()
{
    using (PexPConsoleInContext.Create())
    {
      string[] ss = new string[2];
      ss[0] = "?\u0001";
      ss[1] = "?\u0001\0";
      this.Main(ss);
    }
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void MainThrowsArgumentOutOfRangeException63()
{
    string[] ss = new string[2];
    ss[0] = "[\u0001";
    ss[1] = "[^-][^";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException589()
{
    string[] ss = new string[2];
    ss[0] = "?\u0001";
    ss[1] = "?\u0001*";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException797()
{
    string[] ss = new string[2];
    ss[0] = "[\u0001";
    ss[1] = "[-@@n@@n";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException598()
{
    string[] ss = new string[2];
    ss[0] = "[\u0001";
    ss[1] = "[-@@@@t1-\u0001";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException96()
{
    string[] ss = new string[2];
    ss[0] = "[\u0001";
    ss[1] = "[-@@@@t1-1";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void MainThrowsIndexOutOfRangeException896()
{
    string[] ss = new string[2];
    ss[0] = "[\u0001";
    ss[1] = "[-@@@@t9-x";
    this.Main(ss);
}
    }
}
