// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Edu.Nlu.Sir.Siemens.Replace
{
    public partial class BaseVersionTest
    {
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void locateThrowsNullReferenceException946()
{
    bool b;
    b = this.locate(' ', (string)null, 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void locate132()
{
    bool b;
    b = this.locate(' ', "\0", 0);
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void locate604()
{
    bool b;
    b = this.locate(' ', "\u0001\0\0", 0);
    Assert.AreEqual<bool>(false, b);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void locate754()
{
    bool b;
    b = this.locate(' ', "\u0001 ", 0);
    Assert.AreEqual<bool>(true, b);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void locate999()
{
    bool b;
    b = this.locate('A', "\u0002\0@", 0);
    Assert.AreEqual<bool>(false, b);
}
    }
}
