// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Edu.Nlu.Sir.Siemens.Replace
{
    public partial class BaseVersionTest
    {
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void getpatThrowsNullReferenceException164()
{
    bool b;
    string s = (string)null;
    b = this.getpat((string)null, out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void getpatThrowsIndexOutOfRangeException598()
{
    bool b;
    string s = (string)null;
    b = this.getpat("\0", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void getpatThrowsIndexOutOfRangeException111()
{
    bool b;
    string s = (string)null;
    b = this.getpat("[\u0001", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void getpatThrowsIndexOutOfRangeException656()
{
    bool b;
    string s = (string)null;
    b = this.getpat("%\u0001", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void getpat954()
{
    bool b;
    string s = (string)null;
    b = this.getpat("\0\u0001", out s);
    Assert.AreEqual<bool>(false, b);
    Assert.AreEqual<string>("\0", s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void getpatThrowsIndexOutOfRangeException966()
{
    bool b;
    string s = (string)null;
    b = this.getpat("*\u0001", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void getpatThrowsIndexOutOfRangeException622()
{
    bool b;
    string s = (string)null;
    b = this.getpat("\u0001\u0001", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void getpatThrowsIndexOutOfRangeException637()
{
    bool b;
    string s = (string)null;
    b = this.getpat("$\u0001", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void getpatThrowsArgumentOutOfRangeException377()
{
    bool b;
    string s = (string)null;
    b = this.getpat("[\u0001\0", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void getpatThrowsIndexOutOfRangeException736()
{
    bool b;
    string s = (string)null;
    b = this.getpat("%?", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void getpatThrowsIndexOutOfRangeException936()
{
    bool b;
    string s = (string)null;
    b = this.getpat("[]", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void getpatThrowsIndexOutOfRangeException342()
{
    bool b;
    string s = (string)null;
    b = this.getpat("[-", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void getpatThrowsIndexOutOfRangeException651()
{
    bool b;
    string s = (string)null;
    b = this.getpat("@\u0001", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void getpatThrowsIndexOutOfRangeException473()
{
    bool b;
    string s = (string)null;
    b = this.getpat("[^", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void getpatThrowsIndexOutOfRangeException139()
{
    bool b;
    string s = (string)null;
    b = this.getpat("@t", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void getpatThrowsIndexOutOfRangeException65101()
{
    bool b;
    string s = (string)null;
    b = this.getpat("[\u0001\u0001", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void getpatThrowsIndexOutOfRangeException241()
{
    bool b;
    string s = (string)null;
    b = this.getpat("@n", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void getpatThrowsIndexOutOfRangeException408()
{
    bool b;
    string s = (string)null;
    b = this.getpat("[@\u0001", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void getpatThrowsArgumentOutOfRangeException490()
{
    bool b;
    string s = (string)null;
    b = this.getpat("[@@\0", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void getpatThrowsIndexOutOfRangeException422()
{
    bool b;
    string s = (string)null;
    b = this.getpat("$$", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void getpatThrowsIndexOutOfRangeException740()
{
    bool b;
    string s = (string)null;
    b = this.getpat("%??", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void getpatThrowsIndexOutOfRangeException339()
{
    bool b;
    string s = (string)null;
    b = this.getpat("%%", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void getpat924()
{
    bool b;
    string s = (string)null;
    b = this.getpat("%*", out s);
    Assert.AreEqual<bool>(false, b);
    Assert.AreEqual<string>("%\0", s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void getpatThrowsArgumentOutOfRangeException472()
{
    bool b;
    string s = (string)null;
    b = this.getpat("[-\0", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void getpatThrowsIndexOutOfRangeException610()
{
    bool b;
    string s = (string)null;
    b = this.getpat("[-\u0001", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void getpatThrowsIndexOutOfRangeException63701()
{
    bool b;
    string s = (string)null;
    b = this.getpat("**", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void getpatThrowsIndexOutOfRangeException639()
{
    bool b;
    string s = (string)null;
    b = this.getpat("$\u0001*", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void getpatThrowsArgumentOutOfRangeException233()
{
    bool b;
    string s = (string)null;
    b = this.getpat("$*\0", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void getpatThrowsIndexOutOfRangeException581()
{
    bool b;
    string s = (string)null;
    b = this.getpat("$**", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void getpatThrowsIndexOutOfRangeException42201()
{
    bool b;
    string s = (string)null;
    b = this.getpat("[--", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void getpat970()
{
    bool b;
    string s = (string)null;
    b = this.getpat("%$\0", out s);
    Assert.AreEqual<bool>(true, b);
    Assert.AreEqual<string>("%$\0", s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void getpatThrowsIndexOutOfRangeException34()
{
    bool b;
    string s = (string)null;
    b = this.getpat("[-][", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void getpatThrowsArgumentOutOfRangeException184()
{
    bool b;
    string s = (string)null;
    b = this.getpat("[-][\0", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void getpatThrowsIndexOutOfRangeException794()
{
    bool b;
    string s = (string)null;
    b = this.getpat("%?*", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void getpatThrowsArgumentOutOfRangeException914()
{
    bool b;
    string s = (string)null;
    b = this.getpat("[^-][^", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void getpatThrowsIndexOutOfRangeException732()
{
    bool b;
    string s = (string)null;
    b = this.getpat("[--\u0001", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void getpatThrowsIndexOutOfRangeException690()
{
    bool b;
    string s = (string)null;
    b = this.getpat("[@@@\u0001", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void getpatThrowsIndexOutOfRangeException726()
{
    bool b;
    string s = (string)null;
    b = this.getpat("[@@@@", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void getpatThrowsIndexOutOfRangeException725()
{
    bool b;
    string s = (string)null;
    b = this.getpat("[@@@@\u0001", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void getpat326()
{
    bool b;
    string s = (string)null;
    b = this.getpat("$\u0001$$$\0", out s);
    Assert.AreEqual<bool>(true, b);
    Assert.AreEqual<string>("c$c\u0001c$c$$\0", s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void getpatThrowsArgumentOutOfRangeException829()
{
    bool b;
    string s = (string)null;
    b = this.getpat("[^\0\0\0\0", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void getpat807()
{
    bool b;
    string s = (string)null;
    b = this.getpat("$@$$$\0", out s);
    Assert.AreEqual<bool>(true, b);
    Assert.AreEqual<string>("c$c$c$$\0", s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void getpat298()
{
    bool b;
    string s = (string)null;
    b = this.getpat("$@t\0\0\0", out s);
    Assert.AreEqual<bool>(true, b);
    Assert.AreEqual<string>("c$c\t\0", s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void getpat331()
{
    bool b;
    string s = (string)null;
    b = this.getpat("$@n\0\0\0", out s);
    Assert.AreEqual<bool>(true, b);
    Assert.AreEqual<string>("c$c\n\0", s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void getpatThrowsArgumentOutOfRangeException392()
{
    bool b;
    string s = (string)null;
    b = this.getpat("[\u0001\u0001\0\0\0", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void getpat52()
{
    bool b;
    string s = (string)null;
    b = this.getpat("?\0\0", out s);
    Assert.AreEqual<bool>(true, b);
    Assert.AreEqual<string>("?\0", s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void getpatThrowsArgumentOutOfRangeException99()
{
    bool b;
    string s = (string)null;
    b = this.getpat("[^--\0\0\0\0\0\0\0\0\0\0", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void getpatThrowsArgumentOutOfRangeException74()
{
    bool b;
    string s = (string)null;
    b = this.getpat("[^--\u0001\0\0\0\0\0\0\0", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void getpat912()
{
    bool b;
    string s = (string)null;
    b = this.getpat("%\u0001%%%\0", out s);
    Assert.AreEqual<bool>(true, b);
    Assert.AreEqual<string>("%c\u0001c%c%c%\0", s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void getpat378()
{
    bool b;
    string s = (string)null;
    b = this.getpat("?$???\0", out s);
    Assert.AreEqual<bool>(true, b);
    Assert.AreEqual<string>("?c$???\0", s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void getpatThrowsIndexOutOfRangeException734()
{
    bool b;
    string s = (string)null;
    b = this.getpat("$**$$\0", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void getpatThrowsArgumentOutOfRangeException611()
{
    bool b;
    string s = (string)null;
    b = this.getpat("$\u0001\u0001$$*$$$$$\0", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void getpatThrowsArgumentOutOfRangeException628()
{
    bool b;
    string s = (string)null;
    b = this.getpat("$[^][^\0\0\0\0\0\0", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void getpatThrowsArgumentOutOfRangeException111()
{
    bool b;
    string s = (string)null;
    b = this.getpat("?*???\0", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void getpatThrowsArgumentOutOfRangeException717()
{
    bool b;
    string s = (string)null;
    b = this.getpat("[@@@\u0001\0\0\0\0\0\0\0", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void getpatThrowsArgumentOutOfRangeException624()
{
    bool b;
    string s = (string)null;
    b = this.getpat("$\u0001[^\u0001\u0001\u00011-\u0001$$$$$$$$$$$$$\0", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void getpatThrowsArgumentOutOfRangeException280()
{
    bool b;
    string s = (string)null;
    b = this.getpat("$\u0001[^\u0001\u0001\u00011-1$$$$$$$$$$$$$\0", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void getpatThrowsArgumentOutOfRangeException494()
{
    bool b;
    string s = (string)null;
    b = this.getpat("$\u0001[^\u0001\u0001\u00016-p$$$$$$$$$$$$$\0", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void getpatThrowsArgumentOutOfRangeException859()
{
    bool b;
    string s = (string)null;
    b = this.getpat("[@@@@\0\0\0\0\0\0\0", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void getpatThrowsArgumentOutOfRangeException541()
{
    bool b;
    string s = (string)null;
    b = this.getpat("[@@@@\u0001\0\0\0\0\0\0", out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void getpat905()
{
    bool b;
    string s = (string)null;
    b = this.getpat
            ("$\u0001\u0001$$\u0001%$$$\u0001$$$$$$$$$%$$$$$$$$$$$$$$$$$$?$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$\0", 
             out s);
    Assert.AreEqual<bool>(false, b);
    Assert.AreEqual<string>
        ("c$c\u0001c\u0001c$c$c\u0001c%c$c$c$c\u0001c$c$c$c$c$c$c$c$c$c%c$c$c$c$c$c$c$c$c$c$c$c$c$c$c$c$c$c$?c$c$c$c$c$c$c$c$c$c$c", 
         s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void getpat73()
{
    bool b;
    string s = (string)null;
    b = this.getpat("$\u0001\u0001$$@t$$@t$$$$$$$$$$$$\0", out s);
    Assert.AreEqual<bool>(true, b);
    Assert.AreEqual<string>("c$c\u0001c\u0001c$c$c\tc$c$c\tc$c$c$c$c$c$c$c$c$c$c$$\0", s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void getpat980()
{
    bool b;
    string s = (string)null;
    b = this.getpat
            ("$\u0001[^\u0001\u0001\u0001@\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001@\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001@\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u00019-8\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u00011-\u0001$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$\0", 
             out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void getpat26()
{
    bool b;
    string s = (string)null;
    b = this.getpat
            ("$\u0001[^\u0001\u0001\u0001@\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001@\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001@\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u00019-8\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u0001\u00011-1$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$\0", 
             out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void getpat642()
{
    bool b;
    string s = (string)null;
    b = this.getpat
            ("$\u0001\u0001$$\u0001%$$$\u0001$$$$$$$$$%$$$$$$$$$$$$$$$$$$?$$$$$$$$%$[$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$\0", 
             out s);
    Assert.AreEqual<bool>(false, b);
    Assert.AreEqual<string>
        ("c$c\u0001c\u0001c$c$c\u0001c%c$c$c$c\u0001c$c$c$c$c$c$c$c$c$c%c$c$c$c$c$c$c$c$c$c$c$c$c$c$c$c$c$c$?c$c$c$c$c$c$c$c$c%c$", 
         s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void getpatThrowsArgumentOutOfRangeException121()
{
    bool b;
    string s = (string)null;
    b = this.getpat("[-7-9-x\0\0\0\0\0", out s);
}
    }
}
