// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Edu.Nlu.Sir.Siemens.Replace
{
    public partial class BaseVersionTest
    {
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void makepatThrowsNullReferenceException777()
{
    int i;
    string s = (string)null;
    i = this.makepat((string)null, 0, '@', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException821()
{
    int i;
    string s = (string)null;
    i = this.makepat("", 0, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException544()
{
    int i;
    string s = (string)null;
    i = this.makepat("\0", -1, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void makepat833()
{
    int i;
    string s = (string)null;
    i = this.makepat("! ", 0, '!', out s);
    Assert.AreEqual<int>(0, i);
    Assert.AreEqual<string>("\0", s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException540()
{
    int i;
    string s = (string)null;
    i = this.makepat("  ", 0, '!', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException310()
{
    int i;
    string s = (string)null;
    i = this.makepat("? ", 0, '!', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException598()
{
    int i;
    string s = (string)null;
    i = this.makepat("[ ", 0, '!', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException80()
{
    int i;
    string s = (string)null;
    i = this.makepat("$ ", 0, '!', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException752()
{
    int i;
    string s = (string)null;
    i = this.makepat("[^", 0, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException350()
{
    int i;
    string s = (string)null;
    i = this.makepat("[]", 0, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void makepatThrowsArgumentOutOfRangeException601()
{
    int i;
    string s = (string)null;
    i = this.makepat("[\0", 0, '!', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException823()
{
    int i;
    string s = (string)null;
    i = this.makepat("?%", 0, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException825()
{
    int i;
    string s = (string)null;
    i = this.makepat("?*", 0, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException499()
{
    int i;
    string s = (string)null;
    i = this.makepat("[-", 0, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void makepat67()
{
    int i;
    string s = (string)null;
    i = this.makepat("\0 ", 0, '!', out s);
    Assert.AreEqual<int>(0, i);
    Assert.AreEqual<string>("\0", s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException869()
{
    int i;
    string s = (string)null;
    i = this.makepat("@ ", 0, '!', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException656()
{
    int i;
    string s = (string)null;
    i = this.makepat("@n", 0, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException813()
{
    int i;
    string s = (string)null;
    i = this.makepat("@t", 0, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void makepat170()
{
    int i;
    string s = (string)null;
    i = this.makepat("@\0", 0, '!', out s);
    Assert.AreEqual<int>(0, i);
    Assert.AreEqual<string>("c@\0", s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException16()
{
    int i;
    string s = (string)null;
    i = this.makepat("?%?", 0, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException433()
{
    int i;
    string s = (string)null;
    i = this.makepat("?%*", 0, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException126()
{
    int i;
    string s = (string)null;
    i = this.makepat("?%%", 0, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void makepatThrowsArgumentOutOfRangeException535()
{
    int i;
    string s = (string)null;
    i = this.makepat("[!\0", 0, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException448()
{
    int i;
    string s = (string)null;
    i = this.makepat("$*", 0, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void makepatThrowsArgumentOutOfRangeException837()
{
    int i;
    string s = (string)null;
    i = this.makepat("$*\0", 0, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void makepatThrowsArgumentOutOfRangeException110()
{
    int i;
    string s = (string)null;
    i = this.makepat("[-\0", 0, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException543()
{
    int i;
    string s = (string)null;
    i = this.makepat("[-\u0001", 0, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException913()
{
    int i;
    string s = (string)null;
    i = this.makepat("$$", 0, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException419()
{
    int i;
    string s = (string)null;
    i = this.makepat("[!\u0001", 0, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException414()
{
    int i;
    string s = (string)null;
    i = this.makepat("[@\u0001", 0, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException761()
{
    int i;
    string s = (string)null;
    i = this.makepat("$**", 0, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void makepat826()
{
    int i;
    string s = (string)null;
    i = this.makepat("?$ ", 0, ' ', out s);
    Assert.AreEqual<int>(2, i);
    Assert.AreEqual<string>("?$\0", s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException386()
{
    int i;
    string s = (string)null;
    i = this.makepat("[--", 0, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException694()
{
    int i;
    string s = (string)null;
    i = this.makepat("[^--\u0001", 0, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException700()
{
    int i;
    string s = (string)null;
    i = this.makepat("[[-][", 1, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void makepatThrowsArgumentOutOfRangeException840()
{
    int i;
    string s = (string)null;
    i = this.makepat("[-][\0", 0, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void makepatThrowsArgumentOutOfRangeException787()
{
    int i;
    string s = (string)null;
    i = this.makepat("[^-][^", 0, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException855()
{
    int i;
    string s = (string)null;
    i = this.makepat("@!?@\u0001?@", 1, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException610()
{
    int i;
    string s = (string)null;
    i = this.makepat("?!?@\u0001@?", 1, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException354()
{
    int i;
    string s = (string)null;
    i = this.makepat("!?[@@@\u0001", 0, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException54401()
{
    int i;
    string s = (string)null;
    i = this.makepat("n@n@n", 1, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException514()
{
    int i;
    string s = (string)null;
    i = this.makepat("@n*", 0, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException651()
{
    int i;
    string s = (string)null;
    i = this.makepat("!?@\u0001?[\u0001\u0001\u0001\u0001\u00011-\u0001", 0, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException644()
{
    int i;
    string s = (string)null;
    i = this.makepat("!?@\u0001?[\u0001\u0001\u0001\u0001\u00011-q", 0, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void makepatThrowsIndexOutOfRangeException191()
{
    int i;
    string s = (string)null;
    i = this.makepat("%", 0, ' ', out s);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void makepat583()
{
    int i;
    string s = (string)null;
    i = this.makepat("%**", 0, ' ', out s);
    Assert.AreEqual<int>(0, i);
    Assert.AreEqual<string>("%\0", s);
}
    }
}
