// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Edu.Nlu.Sir.Siemens.Replace
{
    public partial class BaseVersionTest
    {
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
[Ignore]
[PexDescription("the test state was: system environment exit")]
public void patsizeThrowsExitException422()
{
    int i;
    char[] cs = new char[100];
    i = this.patsize(cs, 0);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void patsize50()
{
    int i;
    char[] cs = new char[100];
    cs[0] = '[';
    i = this.patsize(cs, 0);
    Assert.AreEqual<int>(2, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void patsize719()
{
    int i;
    char[] cs = new char[100];
    cs[0] = '!';
    i = this.patsize(cs, 0);
    Assert.AreEqual<int>(2, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void patsize4()
{
    int i;
    char[] cs = new char[100];
    cs[0] = '$';
    i = this.patsize(cs, 0);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void patsize788()
{
    int i;
    char[] cs = new char[100];
    cs[0] = '?';
    i = this.patsize(cs, 0);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void patsize997()
{
    int i;
    char[] cs = new char[100];
    cs[0] = '*';
    i = this.patsize(cs, 0);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void patsize95()
{
    int i;
    char[] cs = new char[100];
    cs[0] = '%';
    i = this.patsize(cs, 0);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void patsize876()
{
    int i;
    char[] cs = new char[100];
    cs[0] = 'c';
    i = this.patsize(cs, 0);
    Assert.AreEqual<int>(2, i);
}
    }
}
