// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Edu.Unl.Sir.Siemens.PrintTokens2
{
    public partial class originalTest
    {
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void print_token998()
{
    int i;
    i = this.print_token("\0");
    Assert.AreEqual<int>(6, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void print_token580()
{
    int i;
    i = this.print_token(";\0\0");
    Assert.AreEqual<int>(5, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void print_token976()
{
    int i;
    i = this.print_token("\u0001\0\0");
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void print_token11()
{
    int i;
    i = this.print_token("#\0\0");
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void print_token734()
{
    int i;
    i = this.print_token("#P\0\0\0\0");
    Assert.AreEqual<int>(43, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void print_token282()
{
    int i;
    i = this.print_token("1\0\0");
    Assert.AreEqual<int>(41, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void print_token709()
{
    int i;
    i = this.print_token("0\u0001\0\0\0\0");
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void print_token727()
{
    int i;
    i = this.print_token("00\0\0\0\0");
    Assert.AreEqual<int>(41, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void print_token156()
{
    int i;
    i = this.print_token("\"\0\0");
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void print_token501()
{
    int i;
    i = this.print_token("\"\u0001\0\0\0\0");
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void print_token569()
{
    int i;
    i = this.print_token("\"\"\0");
    Assert.AreEqual<int>(42, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void print_token933()
{
    int i;
    i = this.print_token("A\0\0");
    Assert.AreEqual<int>(3, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void print_token480()
{
    int i;
    i = this.print_token("b\u0001\0");
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void print_token288()
{
    int i;
    i = this.print_token("bb\0");
    Assert.AreEqual<int>(3, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void print_token425()
{
    int i;
    i = this.print_token("bb\u0001\0\0\0\0");
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void print_token247()
{
    int i;
    i = this.print_token("bb0\0\0\0\0");
    Assert.AreEqual<int>(3, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void print_token194()
{
    int i;
    i = this.print_token("b0@\0\0\0\0");
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void print_token670()
{
    int i;
    i = this.print_token("bba\0\0\0\0");
    Assert.AreEqual<int>(3, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void print_token605()
{
    int i;
    i = this.print_token("\"\u2000\u0001\"\"\"\0");
    Assert.AreEqual<int>(42, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void print_token645()
{
    int i;
    i = this.print_token("01\u0001\0\0\0\0");
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void print_token989()
{
    int i;
    i = this.print_token("000\u0001\0\0");
    Assert.AreEqual<int>(0, i);
}
    }
}
