// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Edu.Unl.Sir.Siemens.PrintTokens2
{
    public partial class originalTest
    {
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void is_keyword683()
{
    int i;
    i = this.is_keyword("");
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void is_keyword532()
{
    int i;
    i = this.is_keyword("lambda");
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void is_keyword94()
{
    int i;
    i = this.is_keyword("and");
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void is_keyword63()
{
    int i;
    i = this.is_keyword("xor");
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void is_keyword927()
{
    int i;
    i = this.is_keyword("or");
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void is_keyword22()
{
    int i;
    i = this.is_keyword("if");
    Assert.AreEqual<int>(1, i);
}
    }
}
