// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Edu.Unl.Sir.Siemens.PrintTokens2
{
    public partial class originalTest
    {
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void is_spec_symbol683()
{
    int i;
    i = this.is_spec_symbol("");
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void is_spec_symbol580()
{
    int i;
    i = this.is_spec_symbol("`");
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void is_spec_symbol500()
{
    int i;
    i = this.is_spec_symbol(",");
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void is_spec_symbol685()
{
    int i;
    i = this.is_spec_symbol("(");
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void is_spec_symbol279()
{
    int i;
    i = this.is_spec_symbol("]");
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void is_spec_symbol118()
{
    int i;
    i = this.is_spec_symbol(")");
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void is_spec_symbol455()
{
    int i;
    i = this.is_spec_symbol("[");
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void is_spec_symbol359()
{
    int i;
    i = this.is_spec_symbol("\'");
    Assert.AreEqual<int>(1, i);
}
    }
}
