// <copyright file="MaybeTests.Maybe_ValueShouldConvertToSomething.g.cs">Copyright ©  2008</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace FPTests
{
	public partial class MaybeTests
	{
[TestMethod]
[PexGeneratedBy(typeof(MaybeTests))]
public void Maybe_ValueShouldConvertToSomething120()
{
    object s0 = new object();
    this.Maybe_ValueShouldConvertToSomething(s0);
}
	}
}
