// <copyright file="OrdSequenceTests.Test_Ordering.g.cs">Copyright ©  2008</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace FPTests
{
	public partial class OrdSequenceTests
	{
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Ordering213()
{
    int[] ints = new int[0];
    this.Test_Ordering<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Ordering758()
{
    int[] ints = new int[1];
    this.Test_Ordering<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Ordering81()
{
    int[] ints = new int[2];
    ints[0] = 1;
    this.Test_Ordering<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Ordering206()
{
    int[] ints = new int[2];
    ints[0] = 129;
    ints[1] = 640;
    this.Test_Ordering<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Ordering342()
{
    int[] ints = new int[4];
    ints[0] = 966;
    ints[1] = 963;
    ints[2] = 963;
    ints[3] = 963;
    this.Test_Ordering<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Ordering809()
{
    int[] ints = new int[5];
    ints[0] = 2;
    ints[1] = 1;
    ints[2] = 1;
    ints[3] = 1;
    ints[4] = 1;
    this.Test_Ordering<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Ordering45()
{
    int[] ints = new int[6];
    ints[0] = 587;
    ints[1] = 586;
    ints[2] = 586;
    ints[3] = 586;
    ints[4] = 586;
    ints[5] = 586;
    this.Test_Ordering<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Ordering672()
{
    int[] ints = new int[3];
    ints[0] = 6;
    ints[1] = 517;
    this.Test_Ordering<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Ordering192()
{
    int[] ints = new int[8];
    ints[0] = 711;
    ints[1] = -2147482940;
    ints[2] = -2147482940;
    ints[3] = -2147482940;
    ints[4] = -2147482940;
    ints[5] = -2147482940;
    ints[6] = -2147482940;
    this.Test_Ordering<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Ordering570()
{
    int[] ints = new int[10];
    ints[0] = -2145386496;
    ints[1] = -2147483602;
    ints[2] = -2147483602;
    ints[3] = -2147483602;
    ints[4] = -2147483602;
    ints[5] = -2147483602;
    ints[6] = -2147483602;
    ints[7] = -2147479401;
    this.Test_Ordering<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Ordering169()
{
    int[] ints = new int[11];
    ints[0] = -2145386496;
    ints[1] = -2147483602;
    ints[2] = -2147483602;
    ints[3] = -2147483602;
    ints[4] = -2147483602;
    ints[5] = -2147483602;
    ints[6] = -2147483602;
    ints[7] = -2147479401;
    this.Test_Ordering<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Ordering795()
{
    int[] ints = new int[8];
    ints[0] = 2147450911;
    ints[1] = -32739;
    ints[2] = -32739;
    ints[3] = -32739;
    ints[4] = -32739;
    ints[5] = -32739;
    ints[6] = -32739;
    ints[7] = -2147483618;
    this.Test_Ordering<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Ordering363()
{
    int[] ints = new int[4];
    ints[0] = 257;
    ints[1] = 32;
    ints[2] = 257;
    ints[3] = 32;
    this.Test_Ordering<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Ordering121()
{
    int[] ints = new int[11];
    ints[0] = -671086260;
    ints[1] = -715848374;
    ints[2] = -715848374;
    ints[3] = -715848374;
    ints[4] = -715848374;
    ints[5] = -715848374;
    ints[6] = -715848374;
    ints[7] = int.MinValue;
    this.Test_Ordering<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Ordering843()
{
    int[] ints = new int[9];
    ints[1] = -1876951021;
    ints[2] = -1876951021;
    ints[3] = -1876951021;
    ints[4] = -1876951021;
    ints[5] = -1876951021;
    ints[6] = -1876951021;
    ints[7] = 33555073;
    ints[8] = -1876950528;
    this.Test_Ordering<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Ordering36()
{
    int[] ints = new int[10];
    ints[1] = -1876951021;
    ints[2] = -1876951021;
    ints[3] = -1876951021;
    ints[4] = -1876951021;
    ints[5] = -1876951021;
    ints[6] = -1876951021;
    ints[7] = 33555073;
    ints[8] = -1876950528;
    this.Test_Ordering<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Ordering76()
{
    int[] ints = new int[12];
    ints[0] = -246086272;
    ints[1] = -715848374;
    ints[2] = -715848374;
    ints[3] = -715848374;
    ints[4] = -715848374;
    ints[5] = -715848374;
    ints[6] = -715848374;
    ints[7] = int.MinValue;
    this.Test_Ordering<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Ordering668()
{
    int[] ints = new int[9];
    ints[0] = 962;
    ints[7] = 963;
    ints[8] = 964;
    this.Test_Ordering<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Ordering957()
{
    int[] ints = new int[12];
    ints[0] = -174762640;
    ints[1] = -715827873;
    ints[2] = -715827873;
    ints[3] = -715827873;
    ints[4] = -715827873;
    ints[5] = -715827873;
    ints[6] = -715827873;
    ints[7] = 890521968;
    ints[8] = int.MinValue;
    ints[9] = -183220898;
    this.Test_Ordering<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Ordering976()
{
    int[] ints = new int[4];
    ints[0] = 996;
    ints[1] = 486;
    ints[2] = 996;
    ints[3] = 996;
    this.Test_Ordering<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Ordering504()
{
    int[] ints = new int[5];
    ints[0] = 703;
    ints[1] = 190;
    ints[2] = 700;
    ints[3] = 700;
    this.Test_Ordering<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Ordering656()
{
    int[] ints = new int[11];
    ints[0] = 2;
    ints[1] = 1;
    ints[2] = 1;
    ints[3] = 1;
    ints[4] = 1;
    ints[5] = 1;
    ints[6] = 1;
    ints[7] = 3;
    ints[8] = 514;
    this.Test_Ordering<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Ordering629()
{
    int[] ints = new int[12];
    ints[0] = 2;
    ints[7] = 2;
    this.Test_Ordering<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Ordering306()
{
    int[] ints = new int[5];
    ints[0] = 902;
    ints[1] = 2;
    ints[2] = 896;
    ints[3] = 896;
    ints[4] = 257;
    this.Test_Ordering<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Ordering908()
{
    int[] ints = new int[11];
    ints[0] = -1073479680;
    ints[1] = -1073741824;
    ints[2] = -1073741824;
    ints[3] = -1073741824;
    ints[4] = -1073741824;
    ints[5] = -1073741824;
    ints[6] = -1073741824;
    ints[7] = 1074007049;
    ints[8] = -2147483646;
    ints[9] = -1073741824;
    this.Test_Ordering<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Ordering950()
{
    int[] ints = new int[12];
    ints[0] = -1073479680;
    ints[1] = -1073741824;
    ints[2] = -1073741824;
    ints[3] = -1073741824;
    ints[4] = -1073741824;
    ints[5] = -1073741824;
    ints[6] = -1073741824;
    ints[7] = 1074007049;
    ints[8] = -2147483646;
    ints[9] = -1073741824;
    this.Test_Ordering<int>(ints);
}
	}
}
