// <copyright file="OrdSequenceTests.Test_Split.g.cs">Copyright ©  2008</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace FPTests
{
	public partial class OrdSequenceTests
	{
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split597()
{
    int[] ints = new int[0];
    this.Test_Split<int>(ints, 0, false);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split993()
{
    int[] ints = new int[0];
    this.Test_Split<int>(ints, 0, true);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split386()
{
    int[] ints = new int[1];
    this.Test_Split<int>(ints, 0, false);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split714()
{
    int[] ints = new int[1];
    this.Test_Split<int>(ints, 0, true);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split641()
{
    int[] ints = new int[1];
    ints[0] = 2;
    this.Test_Split<int>(ints, 512, false);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split171()
{
    int[] ints = new int[1];
    ints[0] = 1;
    this.Test_Split<int>(ints, 0, true);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split955()
{
    int[] ints = new int[2];
    this.Test_Split<int>(ints, 0, false);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split640()
{
    int[] ints = new int[2];
    ints[0] = 1;
    ints[1] = 512;
    this.Test_Split<int>(ints, 0, false);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split888()
{
    int[] ints = new int[2];
    ints[0] = 1;
    ints[1] = 512;
    this.Test_Split<int>(ints, 0, true);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split173()
{
    int[] ints = new int[3];
    ints[0] = 1;
    this.Test_Split<int>(ints, 0, false);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split974()
{
    int[] ints = new int[4];
    ints[0] = 43;
    ints[1] = -2147483606;
    ints[2] = -2147483606;
    ints[3] = -2147483606;
    this.Test_Split<int>(ints, -2147483606, false);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split635()
{
    int[] ints = new int[3];
    ints[0] = 1;
    ints[1] = 512;
    this.Test_Split<int>(ints, 0, false);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split195()
{
    int[] ints = new int[6];
    ints[0] = -2147482626;
    ints[1] = -2147482628;
    ints[2] = -2147482628;
    ints[3] = -2147482628;
    ints[4] = -2147482628;
    ints[5] = -2147482628;
    this.Test_Split<int>(ints, -2147482627, false);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split828()
{
    int[] ints = new int[7];
    ints[0] = -2147482625;
    ints[1] = -2147482628;
    ints[2] = -2147482628;
    ints[3] = -2147482628;
    ints[4] = -2147482628;
    ints[5] = -2147482628;
    ints[6] = -2147482626;
    this.Test_Split<int>(ints, -2147482627, false);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split685()
{
    int[] ints = new int[4];
    ints[0] = -2147483136;
    ints[1] = 1073741835;
    ints[2] = int.MinValue;
    ints[3] = -2147483645;
    this.Test_Split<int>(ints, -2147483647, false);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split563()
{
    int[] ints = new int[3];
    ints[0] = 1023;
    ints[2] = 1023;
    this.Test_Split<int>(ints, 0, false);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split99()
{
    int[] ints = new int[4];
    ints[0] = 331;
    ints[1] = 10;
    ints[2] = 10;
    ints[3] = 136;
    this.Test_Split<int>(ints, 0, false);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split591()
{
    int[] ints = new int[5];
    ints[0] = 643;
    ints[1] = 129;
    ints[2] = 129;
    ints[3] = 512;
    ints[4] = 768;
    this.Test_Split<int>(ints, 0, false);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split291()
{
    int[] ints = new int[6];
    ints[0] = 900;
    ints[1] = 449;
    ints[2] = 449;
    ints[3] = 512;
    ints[4] = 961;
    this.Test_Split<int>(ints, 992, false);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split651()
{
    int[] ints = new int[4];
    ints[0] = -2147483136;
    ints[1] = 513;
    ints[2] = int.MinValue;
    ints[3] = -2147483136;
    this.Test_Split<int>(ints, int.MinValue, false);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split411()
{
    int[] ints = new int[2];
    ints[0] = -2147483363;
    ints[1] = -2147483362;
    this.Test_Split<int>(ints, -2147483363, true);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split636()
{
    int[] ints = new int[6];
    ints[0] = 4;
    ints[3] = 1;
    ints[4] = 514;
    ints[5] = 512;
    this.Test_Split<int>(ints, int.MinValue, false);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split894()
{
    int[] ints = new int[6];
    ints[0] = 1006;
    ints[1] = 986;
    ints[2] = 986;
    ints[3] = 1003;
    ints[4] = 1007;
    ints[5] = 1008;
    this.Test_Split<int>(ints, 0, false);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split630()
{
    int[] ints = new int[5];
    ints[0] = -2147483136;
    ints[1] = 513;
    ints[2] = int.MinValue;
    ints[3] = -2147483136;
    this.Test_Split<int>(ints, int.MinValue, false);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split232()
{
    int[] ints = new int[6];
    ints[0] = 767;
    ints[1] = 734;
    ints[2] = 734;
    ints[3] = 735;
    ints[4] = 769;
    ints[5] = 800;
    this.Test_Split<int>(ints, 832, true);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split273()
{
    int[] ints = new int[6];
    ints[0] = 167;
    ints[1] = 166;
    ints[3] = 166;
    ints[4] = 166;
    this.Test_Split<int>(ints, 0, false);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split364()
{
    int[] ints = new int[4];
    ints[0] = 513;
    ints[1] = 512;
    ints[3] = 512;
    this.Test_Split<int>(ints, 768, true);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split69()
{
    int[] ints = new int[9];
    ints[0] = -2147417854;
    ints[1] = -2147483395;
    ints[2] = -2147483395;
    ints[3] = -2147483395;
    ints[4] = -2147483395;
    ints[5] = -2147483395;
    ints[6] = -2147483391;
    ints[7] = -2147220992;
    ints[8] = -2147483393;
    this.Test_Split<int>(ints, -2146959360, true);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split160()
{
    int[] ints = new int[3];
    ints[0] = 7;
    ints[2] = 5;
    this.Test_Split<int>(ints, 4, false);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split218()
{
    int[] ints = new int[3];
    ints[0] = 3;
    ints[1] = 2;
    this.Test_Split<int>(ints, 0, true);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split895()
{
    int[] ints = new int[10];
    ints[1] = int.MinValue;
    ints[2] = int.MinValue;
    ints[3] = int.MinValue;
    ints[4] = int.MinValue;
    ints[5] = int.MinValue;
    ints[6] = -2147478997;
    ints[7] = 17705;
    ints[8] = -2147482584;
    ints[9] = 10505;
    this.Test_Split<int>(ints, 9233, false);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split283()
{
    int[] ints = new int[4];
    ints[0] = -2147483107;
    ints[1] = -2147483622;
    ints[2] = -2147483107;
    ints[3] = -2147483622;
    this.Test_Split<int>(ints, -2147483568, false);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split879()
{
    int[] ints = new int[6];
    ints[0] = -2147483008;
    ints[1] = int.MinValue;
    ints[2] = int.MinValue;
    ints[3] = -2147483647;
    ints[4] = -2147483007;
    ints[5] = 643;
    this.Test_Split<int>(ints, -2147483136, false);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split316()
{
    int[] ints = new int[8];
    ints[0] = -2147482619;
    ints[1] = -2147483520;
    ints[2] = -2147483520;
    ints[3] = -2147483520;
    ints[4] = -2147483520;
    ints[5] = -2147483520;
    ints[6] = -2147483388;
    ints[7] = -2147482365;
    this.Test_Split<int>(ints, -2147483518, false);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split236()
{
    int[] ints = new int[8];
    ints[0] = -2147482619;
    ints[1] = -2147483520;
    ints[2] = -2147483520;
    ints[3] = -2147483520;
    ints[4] = -2147483520;
    ints[5] = -2147483520;
    ints[6] = -2147483388;
    ints[7] = -2147482365;
    this.Test_Split<int>(ints, -2147483518, true);
}
[TestMethod]
[PexGeneratedBy(typeof(OrdSequenceTests))]
public void Test_Split494()
{
    int[] ints = new int[11];
    ints[0] = 233;
    ints[1] = -2147483527;
    ints[2] = -2147483527;
    ints[3] = -2147483527;
    ints[4] = -2147483527;
    ints[5] = -2147483527;
    ints[6] = 224;
    ints[7] = 259;
    ints[8] = 1023;
    ints[9] = 222;
    ints[10] = 222;
    this.Test_Split<int>(ints, 259, false);
}
	}
}
