// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace FPTests
{
	public partial class RASequenceTests
	{
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_SplitAt598()
{
    int[] ints = new int[1];
    this.Test_SplitAt<int>(ints, 0);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_SplitAt73()
{
    int[] ints = new int[2];
    this.Test_SplitAt<int>(ints, 0);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_SplitAt917()
{
    int[] ints = new int[2];
    this.Test_SplitAt<int>(ints, 1);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_SplitAt639()
{
    int[] ints = new int[3];
    this.Test_SplitAt<int>(ints, 0);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_SplitAt977()
{
    int[] ints = new int[4];
    this.Test_SplitAt<int>(ints, 0);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_SplitAt345()
{
    int[] ints = new int[5];
    this.Test_SplitAt<int>(ints, 0);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_SplitAt580()
{
    int[] ints = new int[6];
    this.Test_SplitAt<int>(ints, 0);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_SplitAt903()
{
    int[] ints = new int[8];
    this.Test_SplitAt<int>(ints, 0);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_SplitAt851()
{
    int[] ints = new int[5];
    this.Test_SplitAt<int>(ints, 4);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_SplitAt326()
{
    int[] ints = new int[11];
    this.Test_SplitAt<int>(ints, 0);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_SplitAt816()
{
    int[] ints = new int[11];
    this.Test_SplitAt<int>(ints, 1);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_SplitAt157()
{
    int[] ints = new int[11];
    this.Test_SplitAt<int>(ints, 7);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_SplitAt611()
{
    int[] ints = new int[5];
    this.Test_SplitAt<int>(ints, 1);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_SplitAt837()
{
    int[] ints = new int[11];
    this.Test_SplitAt<int>(ints, 3);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_SplitAt444()
{
    int[] ints = new int[5];
    this.Test_SplitAt<int>(ints, 2);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_SplitAt45()
{
    int[] ints = new int[11];
    this.Test_SplitAt<int>(ints, 9);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_SplitAt562()
{
    int[] ints = new int[12];
    this.Test_SplitAt<int>(ints, 2);
}
	}
}
