// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace FPTests
{
	public partial class RASequenceTests
	{
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_Reverse598()
{
    int[] ints = new int[0];
    this.Test_Reverse<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_Reverse470()
{
    int[] ints = new int[1];
    this.Test_Reverse<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_Reverse397()
{
    int[] ints = new int[2];
    this.Test_Reverse<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_Reverse661()
{
    int[] ints = new int[3];
    this.Test_Reverse<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_Reverse430()
{
    int[] ints = new int[4];
    this.Test_Reverse<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_Reverse12()
{
    int[] ints = new int[6];
    this.Test_Reverse<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_Reverse913()
{
    int[] ints = new int[8];
    this.Test_Reverse<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
[Ignore]
[PexDescription("the test state was: duplicate path")]
public void Test_Reverse124()
{
    int[] ints = new int[8];
    ints[5] = 1;
    this.Test_Reverse<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_Reverse169()
{
    int[] ints = new int[11];
    this.Test_Reverse<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_Reverse969()
{
    int[] ints = new int[29];
    this.Test_Reverse<int>(ints);
}
	}
}
