// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace FPTests
{
	public partial class RASequenceTests
	{
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_Concat851()
{
    int[] ints = new int[0];
    int[] ints1 = new int[0];
    this.Test_Concat<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_Concat902()
{
    int[] ints = new int[1];
    int[] ints1 = new int[0];
    this.Test_Concat<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_Concat804()
{
    int[] ints = new int[1];
    int[] ints1 = new int[1];
    this.Test_Concat<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_Concat985()
{
    int[] ints = new int[2];
    int[] ints1 = new int[0];
    this.Test_Concat<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_Concat218()
{
    int[] ints = new int[3];
    int[] ints1 = new int[0];
    this.Test_Concat<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_Concat199()
{
    int[] ints = new int[2];
    int[] ints1 = new int[1];
    this.Test_Concat<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_Concat321()
{
    int[] ints = new int[4];
    int[] ints1 = new int[0];
    this.Test_Concat<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_Concat908()
{
    int[] ints = new int[6];
    int[] ints1 = new int[0];
    this.Test_Concat<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_Concat254()
{
    int[] ints = new int[7];
    int[] ints1 = new int[7];
    this.Test_Concat<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_Concat278()
{
    int[] ints = new int[5];
    int[] ints1 = new int[2];
    this.Test_Concat<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_Concat25401()
{
    int[] ints = new int[8];
    int[] ints1 = new int[7];
    this.Test_Concat<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_Concat145()
{
    int[] ints = new int[7];
    int[] ints1 = new int[8];
    this.Test_Concat<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_Concat438()
{
    int[] ints = new int[7];
    int[] ints1 = new int[11];
    this.Test_Concat<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_Concat388()
{
    int[] ints = new int[9];
    int[] ints1 = new int[7];
    this.Test_Concat<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_Concat689()
{
    int[] ints = new int[11];
    int[] ints1 = new int[7];
    this.Test_Concat<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_Concat681()
{
    int[] ints = new int[20];
    int[] ints1 = new int[8];
    this.Test_Concat<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(RASequenceTests))]
public void Test_Concat735()
{
    int[] ints = new int[8];
    int[] ints1 = new int[8];
    this.Test_Concat<int>(ints, ints1);
}
	}
}
