// <copyright file="TreeDictionaryTests.Test_MapPartial.g.cs">Copyright ©  2008</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Framework;
using FP.Core;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace FPTests
{
	public partial class TreeDictionaryTests
	{
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_MapPartial488()
{
    int[] ints = new int[1];
    int[] ints1 = new int[1];
    ints[0] = 1;
    this.Test_MapPartial
        (ints, ints1, 0, PexChoose.CreateDelegate<Func<int, int, Optional<int>>>());
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_MapPartial404()
{
    int[] ints = new int[2];
    int[] ints1 = new int[2];
    ints[0] = 1;
    ints[1] = 512;
    this.Test_MapPartial
        (ints, ints1, 0, PexChoose.CreateDelegate<Func<int, int, Optional<int>>>());
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_MapPartial522()
{
    int[] ints = new int[3];
    int[] ints1 = new int[3];
    ints[0] = 64;
    ints[1] = 577;
    ints[2] = 544;
    this.Test_MapPartial
        (ints, ints1, 0, PexChoose.CreateDelegate<Func<int, int, Optional<int>>>());
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_MapPartial109()
{
    int[] ints = new int[3];
    int[] ints1 = new int[3];
    ints[0] = 3;
    ints[1] = 512;
    ints[2] = 1;
    this.Test_MapPartial
        (ints, ints1, 0, PexChoose.CreateDelegate<Func<int, int, Optional<int>>>());
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_MapPartial19()
{
    int[] ints = new int[4];
    int[] ints1 = new int[4];
    ints[0] = 34;
    ints[1] = 1;
    ints[2] = 33;
    ints[3] = 36;
    this.Test_MapPartial
        (ints, ints1, 0, PexChoose.CreateDelegate<Func<int, int, Optional<int>>>());
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_MapPartial120()
{
    int[] ints = new int[4];
    int[] ints1 = new int[4];
    ints[0] = 33;
    ints[1] = 4;
    ints[2] = 36;
    ints[3] = 5;
    this.Test_MapPartial
        (ints, ints1, 0, PexChoose.CreateDelegate<Func<int, int, Optional<int>>>());
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_MapPartial572()
{
    int[] ints = new int[3];
    int[] ints1 = new int[3];
    ints[0] = 768;
    ints[1] = 257;
    ints[2] = 256;
    this.Test_MapPartial
        (ints, ints1, 258, PexChoose.CreateDelegate<Func<int, int, Optional<int>>>());
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_MapPartial218()
{
    int[] ints = new int[3];
    int[] ints1 = new int[3];
    ints[0] = 1;
    ints[1] = 513;
    ints[2] = 768;
    this.Test_MapPartial
        (ints, ints1, 0, PexChoose.CreateDelegate<Func<int, int, Optional<int>>>());
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_MapPartial220()
{
    int[] ints = new int[14];
    int[] ints1 = new int[14];
    ints[0] = -2013265918;
    ints[1] = -2113929215;
    ints[2] = int.MinValue;
    ints[3] = -2113929208;
    ints[4] = -2080374771;
    ints[5] = -2113929204;
    ints[6] = -1073741568;
    ints[7] = -1073741808;
    ints[8] = -1073741312;
    ints[9] = -1073741296;
    ints[10] = -1073741804;
    ints[11] = -2147483080;
    ints[12] = -2147483104;
    ints[13] = -2147483503;
    this.Test_MapPartial
        (ints, ints1, 0, PexChoose.CreateDelegate<Func<int, int, Optional<int>>>());
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_MapPartial198()
{
    int[] ints = new int[14];
    int[] ints1 = new int[14];
    ints[0] = -2147483128;
    ints[1] = -2147483261;
    ints[2] = -2147483456;
    ints[3] = -2147483512;
    ints[4] = -2147483584;
    ints[5] = -2147483640;
    ints[6] = -2147483245;
    ints[7] = -2147482991;
    ints[8] = -2147482990;
    ints[9] = -2147482966;
    ints[10] = -2147482717;
    ints[11] = -2147482743;
    ints[12] = -2147483262;
    ints[13] = -2147483319;
    this.Test_MapPartial
        (ints, ints1, 0, PexChoose.CreateDelegate<Func<int, int, Optional<int>>>());
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_MapPartial658()
{
    int[] ints = new int[15];
    int[] ints1 = new int[15];
    ints[0] = -2147483391;
    ints[1] = -2147483647;
    ints[2] = -2147483642;
    ints[3] = -2147483641;
    ints[4] = -2147483646;
    ints[5] = -2147483645;
    ints[6] = -2147483392;
    ints[7] = -2147483385;
    ints[8] = -2147483135;
    ints[9] = -2147483379;
    ints[10] = -2147483616;
    ints[11] = int.MinValue;
    ints[12] = -2147483643;
    ints[13] = -2147483644;
    ints[14] = -2147483600;
    this.Test_MapPartial
        (ints, ints1, 0, PexChoose.CreateDelegate<Func<int, int, Optional<int>>>());
}
	}
}
