// <copyright file="TreeDictionaryTests.Test_Map.g.cs">Copyright ©  2008</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Framework;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace FPTests
{
	public partial class TreeDictionaryTests
	{
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Map538()
{
    int[] ints = new int[1];
    int[] ints1 = new int[1];
    this.Test_Map(ints, ints1, PexChoose.CreateDelegate<Func<int, int, int>>());
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Map396()
{
    IPexChoiceRecorder choices = PexChoose.Replay.Setup();
    int[] ints = new int[1];
    int[] ints1 = new int[1];
    ints1[0] = 1;
    this.Test_Map(ints, ints1, PexChoose.CreateDelegate<Func<int, int, int>>());
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Map22()
{
    int[] ints = new int[2];
    int[] ints1 = new int[2];
    ints[0] = 1;
    this.Test_Map(ints, ints1, PexChoose.CreateDelegate<Func<int, int, int>>());
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Map812()
{
    IPexChoiceRecorder choices = PexChoose.Replay.Setup();
    int[] ints = new int[2];
    int[] ints1 = new int[2];
    ints[0] = 16;
    ints1[0] = 104;
    this.Test_Map(ints, ints1, PexChoose.CreateDelegate<Func<int, int, int>>());
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Map83()
{
    int[] ints = new int[2];
    int[] ints1 = new int[2];
    ints[0] = 974;
    ints[1] = 975;
    this.Test_Map(ints, ints1, PexChoose.CreateDelegate<Func<int, int, int>>());
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Map400()
{
    IPexChoiceRecorder choices = PexChoose.Replay.Setup();
    int[] ints = new int[2];
    int[] ints1 = new int[2];
    ints[0] = 1;
    ints1[0] = 2;
    this.Test_Map(ints, ints1, PexChoose.CreateDelegate<Func<int, int, int>>());
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Map509()
{
    IPexChoiceRecorder choices = PexChoose.Replay.Setup();
    choices.DefaultSession
        .At(1, "result", (object)24576);
    int[] ints = new int[2];
    int[] ints1 = new int[2];
    ints[0] = 12616325;
    ints[1] = 8916416;
    ints1[0] = 6969482;
    ints1[1] = 4284760;
    this.Test_Map(ints, ints1, PexChoose.CreateDelegate<Func<int, int, int>>());
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Map10()
{
    int[] ints = new int[3];
    int[] ints1 = new int[3];
    ints[0] = 1;
    ints[1] = 9;
    ints[2] = 8;
    this.Test_Map(ints, ints1, PexChoose.CreateDelegate<Func<int, int, int>>());
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Map569()
{
    int[] ints = new int[4];
    int[] ints1 = new int[4];
    ints[1] = 2;
    ints[2] = 66;
    ints[3] = 67;
    this.Test_Map(ints, ints1, PexChoose.CreateDelegate<Func<int, int, int>>());
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Map761()
{
    int[] ints = new int[3];
    int[] ints1 = new int[3];
    ints[0] = 513;
    ints[1] = 1;
    this.Test_Map(ints, ints1, PexChoose.CreateDelegate<Func<int, int, int>>());
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Map348()
{
    int[] ints = new int[3];
    int[] ints1 = new int[3];
    ints[0] = 7;
    ints[1] = 2;
    ints[2] = 3;
    this.Test_Map(ints, ints1, PexChoose.CreateDelegate<Func<int, int, int>>());
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Map442()
{
    int[] ints = new int[4];
    int[] ints1 = new int[4];
    ints[0] = 1;
    ints[1] = 2;
    ints[3] = 3;
    this.Test_Map(ints, ints1, PexChoose.CreateDelegate<Func<int, int, int>>());
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Map826()
{
    int[] ints = new int[5];
    int[] ints1 = new int[5];
    ints[0] = 256;
    ints[1] = 259;
    ints[2] = 257;
    ints[3] = 1;
    this.Test_Map(ints, ints1, PexChoose.CreateDelegate<Func<int, int, int>>());
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Map96()
{
    IPexChoiceRecorder choices = PexChoose.Replay.Setup();
    choices.DefaultSession
        .At(0, "result", (object)512)
        .At(1, "result", (object)32);
    int[] ints = new int[2];
    int[] ints1 = new int[2];
    ints[0] = 290;
    ints[1] = 83;
    ints1[0] = 512;
    this.Test_Map(ints, ints1, PexChoose.CreateDelegate<Func<int, int, int>>());
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Map167()
{
    IPexChoiceRecorder choices = PexChoose.Replay.Setup();
    int[] ints = new int[2];
    int[] ints1 = new int[2];
    ints[0] = 154;
    ints[1] = 256;
    ints1[1] = 820;
    this.Test_Map(ints, ints1, PexChoose.CreateDelegate<Func<int, int, int>>());
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Map986()
{
    int[] ints = new int[6];
    int[] ints1 = new int[6];
    ints[0] = -2147482880;
    ints[1] = -2147483392;
    ints[2] = -2147483391;
    ints[3] = -2147483647;
    ints[4] = -2147483135;
    ints[5] = -2147483328;
    this.Test_Map(ints, ints1, PexChoose.CreateDelegate<Func<int, int, int>>());
}
	}
}
