// <copyright file="TreeDictionaryTests.Test_Enumeration.g.cs">Copyright ©  2008</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace FPTests
{
	public partial class TreeDictionaryTests
	{
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Enumeration367()
{
    int[] ints = new int[0];
    int[] ints1 = new int[0];
    this.Test_Enumeration<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Enumeration619()
{
    int[] ints = new int[1];
    int[] ints1 = new int[1];
    this.Test_Enumeration<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Enumeration25()
{
    int[] ints = new int[2];
    int[] ints1 = new int[2];
    ints[0] = 1;
    this.Test_Enumeration<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Enumeration843()
{
    int[] ints = new int[2];
    int[] ints1 = new int[2];
    ints[0] = 1;
    ints[1] = 512;
    this.Test_Enumeration<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Enumeration687()
{
    int[] ints = new int[3];
    int[] ints1 = new int[3];
    ints[1] = 1;
    ints[2] = 2;
    this.Test_Enumeration<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Enumeration645()
{
    int[] ints = new int[3];
    int[] ints1 = new int[3];
    ints[0] = 2;
    ints[1] = 67;
    ints[2] = 64;
    this.Test_Enumeration<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Enumeration584()
{
    int[] ints = new int[4];
    int[] ints1 = new int[4];
    ints[1] = 2;
    ints[2] = 4;
    ints[3] = 5;
    this.Test_Enumeration<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Enumeration38()
{
    int[] ints = new int[4];
    int[] ints1 = new int[4];
    ints[0] = 64;
    ints[1] = 32;
    ints[3] = 1;
    this.Test_Enumeration<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Enumeration345()
{
    int[] ints = new int[4];
    int[] ints1 = new int[4];
    ints[0] = 512;
    ints[2] = 256;
    ints[3] = 1;
    this.Test_Enumeration<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Enumeration891()
{
    int[] ints = new int[4];
    int[] ints1 = new int[4];
    ints[0] = 387;
    ints[1] = 258;
    ints[2] = 384;
    this.Test_Enumeration<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Enumeration65()
{
    int[] ints = new int[4];
    int[] ints1 = new int[4];
    ints[0] = 5;
    ints[2] = 258;
    ints[3] = 1;
    this.Test_Enumeration<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Enumeration37()
{
    int[] ints = new int[5];
    int[] ints1 = new int[5];
    ints[0] = 131;
    ints[1] = 128;
    ints[2] = 130;
    ints[3] = 18;
    ints[4] = 17;
    this.Test_Enumeration<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Enumeration372()
{
    int[] ints = new int[6];
    int[] ints1 = new int[6];
    ints[0] = -2147483264;
    ints[1] = -2145386367;
    ints[2] = -2145386496;
    ints[3] = 67108995;
    ints[4] = 2097282;
    ints[5] = -2146435071;
    this.Test_Enumeration<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Enumeration292()
{
    int[] ints = new int[7];
    int[] ints1 = new int[7];
    ints[0] = -1879048192;
    ints[1] = -2147482624;
    ints[2] = -2147483647;
    ints[3] = -1073741822;
    ints[5] = 134218912;
    ints[6] = 1664;
    this.Test_Enumeration<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Enumeration323()
{
    int[] ints = new int[7];
    int[] ints1 = new int[7];
    ints[0] = -2147483007;
    ints[1] = -2147483584;
    ints[2] = -2147483520;
    ints[3] = -2147483390;
    ints[4] = -2147483386;
    ints[5] = -2147483003;
    ints[6] = -2147483516;
    this.Test_Enumeration<int>(ints, ints1);
}
[TestMethod]
[PexGeneratedBy(typeof(TreeDictionaryTests))]
public void Test_Enumeration627()
{
    int[] ints = new int[13];
    int[] ints1 = new int[13];
    ints[0] = -2147483583;
    ints[1] = -2147483642;
    ints[2] = -2147483376;
    ints[3] = -2147481600;
    ints[4] = -2147481185;
    ints[5] = -2147483392;
    ints[6] = -2147483643;
    ints[7] = int.MinValue;
    ints[8] = -2147483644;
    ints[9] = -2147481216;
    ints[10] = -2147483328;
    ints[11] = -2147483456;
    ints[12] = -2147483519;
    this.Test_Enumeration<int>(ints, ints1);
}
	}
}
