// <copyright file="VectorTests.Test_StoreManyElements.g.cs">Copyright ©  2008</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace FPTests
{
	public partial class VectorTests
	{
[TestMethod]
[PexGeneratedBy(typeof(VectorTests))]
public void Test_StoreManyElements213()
{
    int[] ints = new int[0];
    this.Test_StoreManyElements<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(VectorTests))]
public void Test_StoreManyElements758()
{
    int[] ints = new int[1];
    this.Test_StoreManyElements<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(VectorTests))]
public void Test_StoreManyElements61()
{
    int[] ints = new int[2];
    this.Test_StoreManyElements<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(VectorTests))]
public void Test_StoreManyElements152()
{
    int[] ints = new int[33];
    this.Test_StoreManyElements<int>(ints);
}
[TestMethod]
[PexGeneratedBy(typeof(VectorTests))]
public void Test_StoreManyElements784()
{
    int[] ints = new int[34];
    this.Test_StoreManyElements<int>(ints);
}
	}
}
