// <copyright file="VectorTests.Test_SingleElementVector.g.cs">Copyright ©  2008</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace FPTests
{
	public partial class VectorTests
	{
[TestMethod]
[PexGeneratedBy(typeof(VectorTests))]
public void Test_SingleElementVector466()
{
    this.Test_SingleElementVector<int>(0, 0);
}
[TestMethod]
[PexGeneratedBy(typeof(VectorTests))]
public void Test_SingleElementVector461()
{
    this.Test_SingleElementVector<int>(1, 0);
}
[TestMethod]
[PexGeneratedBy(typeof(VectorTests))]
public void Test_SingleElementVector692()
{
    this.Test_SingleElementVector<int>(32, 0);
}
[TestMethod]
[PexGeneratedBy(typeof(VectorTests))]
public void Test_SingleElementVector703()
{
    this.Test_SingleElementVector<int>(1073741824, 0);
}
[TestMethod]
[PexGeneratedBy(typeof(VectorTests))]
public void Test_SingleElementVector908()
{
    this.Test_SingleElementVector<object>(0, (object)null);
}
[TestMethod]
[PexGeneratedBy(typeof(VectorTests))]
public void Test_SingleElementVector379()
{
    this.Test_SingleElementVector<object>(1, (object)null);
}
[TestMethod]
[PexGeneratedBy(typeof(VectorTests))]
public void Test_SingleElementVector50()
{
    this.Test_SingleElementVector<object>(32, (object)null);
}
[TestMethod]
[PexGeneratedBy(typeof(VectorTests))]
public void Test_SingleElementVector29()
{
    this.Test_SingleElementVector<object>(1073741824, (object)null);
}
	}
}
