// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Edu.Unl.Sir.Siemens.PrintTokens
{
    public partial class OriginalTest
    {
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void next_state895()
{
    int i;
    i = this.next_state(0, (byte)0);
    Assert.AreEqual<int>(-1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void next_state973()
{
    int i;
    i = this.next_state(4, (byte)180);
    Assert.AreEqual<int>(-3, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void next_state813()
{
    int i;
    i = this.next_state(0, (byte)9);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void next_stateThrowsIndexOutOfRangeException543()
{
    int i;
    i = this.next_state(-2147483600, (byte)0);
}
    }
}
