// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Edu.Unl.Sir.Siemens.PrintTokens
{
    public partial class OriginalTest
    {
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void get_actual_token786()
{
    byte[] bs = new byte[1];
    this.get_actual_token(bs, 0);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void get_actual_token580()
{
    byte[] bs = new byte[3];
    this.get_actual_token(bs, 2);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void get_actual_token164()
{
    byte[] bs = new byte[3];
    bs[0] = (byte)9;
    bs[1] = (byte)137;
    bs[2] = (byte)9;
    this.get_actual_token(bs, 2);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void get_actual_token453()
{
    byte[] bs = new byte[3];
    bs[1] = (byte)9;
    this.get_actual_token(bs, 2);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void get_actual_token726()
{
    byte[] bs = new byte[7];
    bs[0] = (byte)9;
    bs[1] = (byte)9;
    bs[2] = (byte)9;
    bs[3] = (byte)160;
    bs[4] = (byte)73;
    bs[5] = (byte)9;
    this.get_actual_token(bs, 6);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void get_actual_token172()
{
    byte[] bs = new byte[3];
    bs[0] = (byte)9;
    bs[1] = (byte)9;
    this.get_actual_token(bs, 2);
}
    }
}
