// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.IO;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Edu.Unl.Sir.Siemens.PrintTokens2.Orig
{
    public partial class originalTest
    {
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void get_charThrowsNullReferenceException264()
{
    char c;
    c = this.get_char((Stream)null);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void get_char703()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      MemoryStream memoryStream;
      char c;
      byte[] bs = new byte[0];
      memoryStream = new MemoryStream(bs, false);
      disposables.Add((IDisposable)memoryStream);
      c = this.get_char((Stream)memoryStream);
      disposables.Dispose();
      Assert.AreEqual<char>('\uffff', c);
    }
}
    }
}
