// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Edu.Unl.Sir.Siemens.PrintTokens2.Orig
{
    public partial class originalTest
    {
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void is_eof_tokenThrowsNullReferenceException797()
{
    int i;
    i = this.is_eof_token((string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
[PexRaisedException(typeof(IndexOutOfRangeException))]
public void is_eof_tokenThrowsIndexOutOfRangeException410()
{
    int i;
    i = this.is_eof_token("");
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void is_eof_token498()
{
    int i;
    i = this.is_eof_token("\0");
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void is_eof_token158()
{
    int i;
    i = this.is_eof_token("\u0001");
    Assert.AreEqual<int>(1, i);
}
    }
}
