// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Edu.Unl.Sir.Siemens.PrintTokens2.Orig
{
    public partial class originalTest
    {
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void token_typeThrowsNullReferenceException233()
{
    int i;
    i = this.token_type((string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void token_type319()
{
    int i;
    i = this.token_type("");
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void token_type597()
{
    int i;
    i = this.token_type("lambda");
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void token_type507()
{
    int i;
    i = this.token_type("if");
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void token_type504()
{
    int i;
    i = this.token_type("and");
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void token_type581()
{
    int i;
    i = this.token_type("or");
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void token_type217()
{
    int i;
    i = this.token_type("xor");
    Assert.AreEqual<int>(1, i);
}
    }
}
