// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Edu.Unl.Sir.Siemens.PrintTokens2.Orig
{
    public partial class originalTest
    {
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void print_spec_symbolThrowsNullReferenceException838()
{
    this.print_spec_symbol((string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void print_spec_symbol153()
{
    this.print_spec_symbol("");
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void print_spec_symbol857()
{
    this.print_spec_symbol("\'");
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void print_spec_symbol617()
{
    this.print_spec_symbol("`");
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void print_spec_symbol98()
{
    this.print_spec_symbol("[");
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void print_spec_symbol774()
{
    this.print_spec_symbol("(");
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void print_spec_symbol657()
{
    this.print_spec_symbol(")");
}
[TestMethod]
[PexGeneratedBy(typeof(originalTest))]
public void print_spec_symbol891()
{
    this.print_spec_symbol("]");
}
    }
}
