// <copyright file="UndirectedGraphTVertexTEdgeTest.RemoveEdge.g.cs" company="MSIT">Copyright © MSIT 2007</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using System.Collections.Generic;

namespace QuickGraph
{
    public partial class UndirectedGraphTVertexTEdgeTest
    {
[TestMethod]
[PexGeneratedBy(typeof(UndirectedGraphTVertexTEdgeTest))]
[PexRaisedException(typeof(KeyNotFoundException))]
public void RemoveEdgeThrowsKeyNotFoundException79()
{
    UndirectedGraph<int, Edge<int>> undirectedGraph;
    Edge<int> edge;
    bool b;
    undirectedGraph = new UndirectedGraph<int, Edge<int>>
                          (false, (EdgeEqualityComparer<int, Edge<int>>)null);
    undirectedGraph.EdgeCapacity = 0;
    edge = EdgeFactory.Create(0, 0);
    b = this.RemoveEdge<int, Edge<int>>(undirectedGraph, edge);
}
[TestMethod]
[PexGeneratedBy(typeof(UndirectedGraphTVertexTEdgeTest))]
[PexRaisedException(typeof(KeyNotFoundException))]
public void RemoveEdgeThrowsKeyNotFoundException860()
{
    UndirectedGraph<int, SEdge<int>> undirectedGraph;
    bool b;
    undirectedGraph = UndirectedGraphFactory.Create(false);
    b = this.RemoveEdge<int, SEdge<int>>(undirectedGraph, default(SEdge<int>));
}
    }
}
