// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Edu.Unl.Sir.Siemens.PrintTokens.Orig
{
    public partial class OriginalTest
    {
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void print_tokenThrowsNullReferenceException639()
{
    int i;
    i = this.print_token((Token)null);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token813()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 0;
    i = this.print_token(token);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token610()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 2;
    i = this.print_token(token);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token50()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 512;
    i = this.print_token(token);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token267()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 31;
    i = this.print_token(token);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token851()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 32;
    i = this.print_token(token);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token967()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 30;
    i = this.print_token(token);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token173()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 29;
    i = this.print_token(token);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token960()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 22;
    i = this.print_token(token);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token295()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 21;
    i = this.print_token(token);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token811()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 26;
    i = this.print_token(token);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token868()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 25;
    i = this.print_token(token);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token62()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 5;
    i = this.print_token(token);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token708()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 6;
    i = this.print_token(token);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token826()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 4;
    i = this.print_token(token);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token653()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 20;
    i = this.print_token(token);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token767()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 3;
    i = this.print_token(token);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token735()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 19;
    i = this.print_token(token);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token189()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 14;
    i = this.print_token(token);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token839()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 13;
    i = this.print_token(token);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token452()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 16;
    i = this.print_token(token);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token428()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 8;
    i = this.print_token(token);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token117()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 24;
    i = this.print_token(token);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token487()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 12;
    i = this.print_token(token);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token376()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 28;
    i = this.print_token(token);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token791()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 27;
    i = this.print_token(token);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token6201()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 11;
    i = this.print_token(token);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token378()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 1;
    i = this.print_token(token);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token297()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 10;
    i = this.print_token(token);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token257()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 18;
    i = this.print_token(token);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token486()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 17;
    i = this.print_token(token);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token747()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 9;
    i = this.print_token(token);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token146()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 7;
    i = this.print_token(token);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token390()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 23;
    i = this.print_token(token);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token975()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 15;
    i = this.print_token(token);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void print_token355()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = -1;
    i = this.print_token(token);
    Assert.AreEqual<int>(1, i);
}
    }
}
