// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Edu.Unl.Sir.Siemens.PrintTokens.Orig
{
    public partial class OriginalTest
    {
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void is_eof_tokenThrowsNullReferenceException21()
{
    int i;
    i = this.is_eof_token((Token)null);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void is_eof_token206()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 0;
    i = this.is_eof_token(token);
    Assert.AreEqual<int>(1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void is_eof_token199()
{
    Token token;
    int i;
    token = new Token();
    token.token_string = (byte[])null;
    token.token_id = 2;
    i = this.is_eof_token(token);
    Assert.AreEqual<int>(0, i);
}
    }
}
