// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Edu.Unl.Sir.Siemens.PrintTokens.Orig
{
    public partial class OriginalTest
    {
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void keyword737()
{
    int i;
    i = this.keyword(0);
    Assert.AreEqual<int>(-1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void keyword354()
{
    int i;
    i = this.keyword(16);
    Assert.AreEqual<int>(16, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void keyword551()
{
    int i;
    i = this.keyword(6);
    Assert.AreEqual<int>(6, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void keyword141()
{
    int i;
    i = this.keyword(9);
    Assert.AreEqual<int>(9, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void keyword357()
{
    int i;
    i = this.keyword(13);
    Assert.AreEqual<int>(13, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void keyword429()
{
    int i;
    i = this.keyword(11);
    Assert.AreEqual<int>(11, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void keyword61()
{
    int i;
    i = this.keyword(10);
    Assert.AreEqual<int>(-1, i);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void keyword468()
{
    int i;
    i = this.keyword(12);
    Assert.AreEqual<int>(-1, i);
}
    }
}
