// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using System.IO;

namespace Edu.Unl.Sir.Siemens.PrintTokens.Orig
{
    public partial class OriginalTest
    {
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
[PexRaisedException(typeof(ArgumentException))]
public void open_character_streamThrowsArgumentException683()
{
    CharacterStream characterStream;
    characterStream = this.open_character_stream("");
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void open_character_streamThrowsNullReferenceException609()
{
    CharacterStream characterStream;
    characterStream = this.open_character_stream((string)null);
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
[PexRaisedException(typeof(ArgumentException))]
public void open_character_streamThrowsArgumentException923()
{
    CharacterStream characterStream;
    characterStream = this.open_character_stream("\0");
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
[PexRaisedException(typeof(ArgumentException))]
public void open_character_streamThrowsArgumentException830()
{
    CharacterStream characterStream;
    characterStream = this.open_character_stream("\u0001");
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
[PexRaisedException(typeof(ArgumentException))]
public void open_character_streamThrowsArgumentException97()
{
    CharacterStream characterStream;
    characterStream = this.open_character_stream(" ");
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
[PexRaisedException(typeof(ArgumentException))]
public void open_character_streamThrowsArgumentException828()
{
    CharacterStream characterStream;
    characterStream = this.open_character_stream("  ");
}
[TestMethod]
[PexGeneratedBy(typeof(OriginalTest))]
public void open_character_stream335()
{
    CharacterStream characterStream;
    characterStream = this.open_character_stream("\u0400\u4001      ");
    Assert.IsNull((object)characterStream);
}
    }
}
