// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace schedule
{
    public partial class ProgramTest
    {
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
public void init_prio_queue345()
{
    this.init_prio_queue(0, 0);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
public void init_prio_queue815()
{
    this.init_prio_queue(0, 1);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
public void init_prio_queue158()
{
    this.init_prio_queue(0, 2);
}
    }
}
