// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace schedule
{
	public partial class ProgramTest
	{
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
[PexRaisedException(typeof(FormatException))]
public void MainThrowsFormatException923()
{
    string[] ss = new string[4];
    ss[0] = "\0";
    ss[1] = "\0";
    ss[2] = "\0";
    ss[3] = "\0";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
[PexRaisedException(typeof(FormatException))]
public void MainThrowsFormatException638()
{
    string[] ss = new string[4];
    ss[0] = "\u0001";
    ss[1] = "\u0001";
    ss[2] = "\u0001";
    ss[3] = "\u0001";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
[PexRaisedException(typeof(FormatException))]
public void MainThrowsFormatException666()
{
    string[] ss = new string[4];
    ss[0] = "-";
    ss[1] = "-";
    ss[2] = "-";
    ss[3] = "-";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
[PexRaisedException(typeof(FormatException))]
public void MainThrowsFormatException900()
{
    string[] ss = new string[4];
    ss[0] = ":";
    ss[1] = ":";
    ss[2] = ":";
    ss[3] = ":";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
[PexRaisedException(typeof(FormatException))]
public void MainThrowsFormatException498()
{
    string[] ss = new string[4];
    ss[0] = "-\0";
    ss[1] = "-";
    ss[2] = "-";
    ss[3] = "-";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
[PexRaisedException(typeof(FormatException))]
public void MainThrowsFormatException682()
{
    string[] ss = new string[4];
    ss[0] = "-0";
    ss[1] = "-";
    ss[2] = "-";
    ss[3] = "-";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
[PexRaisedException(typeof(FormatException))]
public void MainThrowsFormatException385()
{
    string[] ss = new string[4];
    ss[0] = "-0\0";
    ss[1] = "-";
    ss[2] = "-";
    ss[3] = "-";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
public void Main819()
{
    string[] ss = new string[4];
    ss[0] = "1";
    ss[1] = "1";
    ss[2] = "1";
    ss[3] = "3\r\n7";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
public void Main749()
{
    string[] ss = new string[4];
    ss[0] = "1";
    ss[1] = "1";
    ss[2] = "1";
    ss[3] = "5\r\n7";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
public void Main606()
{
    string[] ss = new string[4];
    ss[0] = "1";
    ss[1] = "1";
    ss[2] = "1";
    ss[3] = "6\r\n7";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
public void Main107()
{
    string[] ss = new string[4];
    ss[0] = "1";
    ss[1] = "1";
    ss[2] = "1";
    ss[3] = "6\r\n1 3\r\n6\r\n7";
    this.Main(ss);
}
	}
}
