// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace schedule
{
	public partial class ProgramTest
	{
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
[PexRaisedException(typeof(FormatException))]
public void MainThrowsFormatException396()
{
    string[] ss = new string[4];
    ss[0] = "\0";
    ss[1] = "\0";
    ss[2] = "\0";
    ss[3] = "\0";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
[PexRaisedException(typeof(FormatException))]
public void MainThrowsFormatException988()
{
    string[] ss = new string[4];
    ss[0] = "\u0001";
    ss[1] = "\u0001";
    ss[2] = "\u0001";
    ss[3] = "\u0001";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
[PexRaisedException(typeof(FormatException))]
public void MainThrowsFormatException996()
{
    string[] ss = new string[4];
    ss[0] = "-";
    ss[1] = "-";
    ss[2] = "-";
    ss[3] = "-";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
[PexRaisedException(typeof(FormatException))]
public void MainThrowsFormatException179()
{
    string[] ss = new string[4];
    ss[0] = ":";
    ss[1] = ":";
    ss[2] = ":";
    ss[3] = ":";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
[PexRaisedException(typeof(FormatException))]
public void MainThrowsFormatException960()
{
    string[] ss = new string[4];
    ss[0] = "-\0";
    ss[1] = "-";
    ss[2] = "-";
    ss[3] = "-";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
[PexRaisedException(typeof(FormatException))]
public void MainThrowsFormatException946()
{
    string[] ss = new string[4];
    ss[0] = "-0";
    ss[1] = "-";
    ss[2] = "-";
    ss[3] = "-";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
[PexRaisedException(typeof(FormatException))]
public void MainThrowsFormatException990()
{
    string[] ss = new string[4];
    ss[0] = "-0\0";
    ss[1] = "-";
    ss[2] = "-";
    ss[3] = "-";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
public void Main980()
{
    string[] ss = new string[4];
    ss[0] = "1";
    ss[1] = "1";
    ss[2] = "1";
    ss[3] = "5\r\n6";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
public void Main199()
{
    string[] ss = new string[4];
    ss[0] = "1";
    ss[1] = "1";
    ss[2] = "1";
    ss[3] = "3\r\n6";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
public void Main175()
{
    string[] ss = new string[4];
    ss[0] = "1";
    ss[1] = "1";
    ss[2] = "1";
    ss[3] = "7\r\n6";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
public void Main481()
{
    string[] ss = new string[4];
    ss[0] = "1";
    ss[1] = "1";
    ss[2] = "1";
    ss[3] = "5\r\n5\r\n4 0.11\r\n6";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
public void Main80()
{
    string[] ss = new string[4];
    ss[0] = "1";
    ss[1] = "1";
    ss[2] = "1";
    ss[3] = "7\r\n7\r\n4 0.11\r\n6";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
public void Main609()
{
    string[] ss = new string[4];
    ss[0] = "1";
    ss[1] = "1";
    ss[2] = "1";
    ss[3] = "7\r\n3\r\n4 0.11\r\n6";
    this.Main(ss);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
public void Main186()
{
    string[] ss = new string[4];
    ss[0] = "1";
    ss[1] = "1";
    ss[2] = "1";
    ss[3] = "1 1\r\n1 2\r\n1 2\r\n6";
    this.Main(ss);
}
	}
}
