// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace schedule
{
    public partial class ProgramTest
    {
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
public void unblock_process567()
{
    this.unblock_process((float)0);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
public void unblock_process56701()
{
    this.unblock_process((float)0);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
public void unblock_process7()
{
    this.unblock_process((float)0.10000000149011612);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
public void unblock_process723()
{
    this.unblock_process((float)double.NegativeInfinity);
}
    }
}
