// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace schedule
{
    public partial class ProgramTest
    {
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
public void upgrade_process_prio321()
{
    this.upgrade_process_prio(0, (float)0);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
public void upgrade_process_prio196()
{
    this.upgrade_process_prio(2, (float)0);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
public void upgrade_process_prio668()
{
    this.upgrade_process_prio(3, (float)0);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
public void upgrade_process_prio732()
{
    this.upgrade_process_prio(1, (float)3.1415927410125732);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
public void upgrade_process_prio73201()
{
    this.upgrade_process_prio(1, (float)3.1415927410125732);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
public void upgrade_process_prio73202()
{
    this.upgrade_process_prio(1, (float)3.1415927410125732);
}
    }
}
