// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace schedule2
{
    public partial class ProgramTest
    {
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
public void put_end597()
{
    int i;
    i = this.put_end(0, (Process)null);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
public void put_end889()
{
    int i;
    Process s0 = new Process();
    s0.pid = 0;
    s0.priority = 0;
    i = this.put_end(3, s0);
    Assert.AreEqual<int>(0, i);
}
    }
}
