// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace schedule2
{
    public partial class ProgramTest
    {
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void readFile661()
{
    ArrayList arrayList;
    arrayList = this.readFile("\0");
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
public void readFile819()
{
    ArrayList arrayList;
    arrayList = this.readFile("input\\ad.1");
    Assert.IsNotNull((object)arrayList);
}
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
public void readFile11()
{
    ArrayList arrayList;
    arrayList = this.readFile("input\\ad.5");
    Assert.IsNotNull((object)arrayList);
}
    }
}
