// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace schedule2
{
    public partial class ProgramTest
    {
[TestMethod]
[PexGeneratedBy(typeof(ProgramTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void Main885()
{
    string[] ss = new string[4];
    ss[0] = "2";
    ss[1] = "2";
    ss[2] = "2";
    ss[3] = "2";
    this.Main(ss);
}
    }
}
