// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Edu.Nlu.Sir.Siemens.TotInfo
{
    public partial class BaseVersionTest
    {
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void QGamma223()
{
    double d;
    d = this.QGamma(0, 0);
    Assert.AreEqual<double>(1, d);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void QGamma760()
{
    double d;
    d = this.QGamma(2.5168894987238294E+17, double.Epsilon);
    Assert.AreEqual<double>(1, d);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void QGamma233()
{
    double d;
    d = this.QGamma(0.33333333333333331, double.Epsilon);
    Assert.AreEqual<double>(1, d);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void QGamma266()
{
    double d;
    d = this.QGamma(0.5, 5853);
    Assert.AreEqual<double>(0, d);
}
    }
}
