// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Edu.Nlu.Sir.Siemens.Replace
{
    public partial class BaseVersionTest
    {
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void putsub630()
{
    char[] cs = new char[100];
    char[] cs1 = new char[100];
    this.putsub(cs, 0, 1, cs1);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void putsub879()
{
    char[] cs = new char[100];
    char[] cs1 = new char[100];
    cs1[0] = 'A';
    cs1[1] = ' ';
    cs1[2] = ' ';
    cs1[3] = ' ';
    cs1[4] = ' ';
    cs1[5] = ' ';
    cs1[6] = ' ';
    cs1[7] = ' ';
    cs1[8] = ' ';
    cs1[9] = ' ';
    cs1[10] = ' ';
    cs1[11] = ' ';
    cs1[12] = ' ';
    cs1[13] = ' ';
    cs1[14] = ' ';
    cs1[15] = ' ';
    cs1[16] = ' ';
    cs1[17] = ' ';
    cs1[18] = ' ';
    cs1[19] = ' ';
    cs1[20] = ' ';
    cs1[21] = ' ';
    cs1[22] = ' ';
    cs1[23] = ' ';
    cs1[24] = ' ';
    cs1[25] = ' ';
    cs1[26] = ' ';
    cs1[27] = ' ';
    cs1[28] = ' ';
    cs1[29] = ' ';
    cs1[30] = ' ';
    cs1[31] = ' ';
    cs1[32] = ' ';
    cs1[33] = ' ';
    cs1[34] = ' ';
    cs1[35] = ' ';
    cs1[36] = ' ';
    cs1[37] = ' ';
    cs1[38] = ' ';
    cs1[39] = ' ';
    cs1[40] = ' ';
    cs1[41] = ' ';
    cs1[42] = ' ';
    cs1[43] = ' ';
    cs1[44] = ' ';
    cs1[45] = ' ';
    cs1[46] = ' ';
    cs1[47] = ' ';
    cs1[48] = ' ';
    cs1[49] = ' ';
    cs1[50] = ' ';
    cs1[51] = ' ';
    cs1[52] = ' ';
    cs1[53] = ' ';
    cs1[55] = ' ';
    cs1[56] = ' ';
    cs1[57] = ' ';
    cs1[58] = ' ';
    cs1[59] = ' ';
    cs1[60] = ' ';
    cs1[61] = ' ';
    cs1[62] = ' ';
    cs1[63] = ' ';
    cs1[64] = ' ';
    cs1[65] = ' ';
    cs1[66] = ' ';
    cs1[67] = ' ';
    cs1[68] = ' ';
    cs1[69] = ' ';
    cs1[70] = ' ';
    cs1[71] = ' ';
    cs1[72] = ' ';
    cs1[73] = ' ';
    cs1[74] = ' ';
    cs1[75] = ' ';
    cs1[76] = ' ';
    cs1[77] = ' ';
    cs1[78] = ' ';
    cs1[79] = ' ';
    cs1[80] = ' ';
    cs1[81] = ' ';
    cs1[82] = ' ';
    cs1[83] = ' ';
    cs1[84] = ' ';
    cs1[85] = ' ';
    cs1[86] = ' ';
    cs1[87] = ' ';
    cs1[88] = ' ';
    cs1[89] = ' ';
    cs1[90] = ' ';
    cs1[91] = ' ';
    cs1[92] = ' ';
    cs1[93] = ' ';
    cs1[94] = ' ';
    cs1[95] = ' ';
    cs1[96] = ' ';
    cs1[97] = ' ';
    cs1[98] = ' ';
    cs1[99] = ' ';
    this.putsub(cs, 0, 1, cs1);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void putsub455()
{
    char[] cs = new char[100];
    char[] cs1 = new char[100];
    cs1[0] = '\uffff';
    this.putsub(cs, 0, 1, cs1);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void putsub811()
{
    char[] cs = new char[100];
    char[] cs1 = new char[100];
    cs1[0] = '\uffff';
    this.putsub(cs, 0, 3, cs1);
}
[TestMethod]
[PexGeneratedBy(typeof(BaseVersionTest))]
public void putsub396()
{
    char[] cs = new char[100];
    char[] cs1 = new char[100];
    cs1[0] = '\uffff';
    cs1[1] = '\uffff';
    this.putsub(cs, 0, 1, cs1);
}
    }
}
